/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { Mag3ntError } from "./mag3nt-error.js";

export type BalanceErrorData = {
  error: string;
  available: components.BalanceErrorAvailable;
  requested: components.Requested;
  network?: string | undefined;
  asset?: string | undefined;
};

export class BalanceError extends Mag3ntError {
  error: string;
  available: components.BalanceErrorAvailable;
  requested: components.Requested;
  network?: string | undefined;
  asset?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: BalanceErrorData;

  constructor(
    err: BalanceErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.available = err.available;
    this.requested = err.requested;
    if (err.network != null) this.network = err.network;
    if (err.asset != null) this.asset = err.asset;

    this.name = "BalanceError";
  }
}

/** @internal */
export const BalanceError$inboundSchema: z.ZodMiniType<BalanceError, unknown> =
  z.pipe(
    z.object({
      error: types.string(),
      available: z.lazy(() => components.BalanceErrorAvailable$inboundSchema),
      requested: z.lazy(() => components.Requested$inboundSchema),
      network: types.optional(types.string()),
      asset: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new BalanceError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
