/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import { Mag3ntError } from "./mag3nt-error.js";

/**
 * Endpoint removed. Migrate to /api/pay.
 */
export type MppPayGoneErrorData = {
  error?: string | undefined;
  migrateTo?: string | undefined;
};

/**
 * Endpoint removed. Migrate to /api/pay.
 */
export class MppPayGoneError extends Mag3ntError {
  error?: string | undefined;
  migrateTo?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: MppPayGoneErrorData;

  constructor(
    err: MppPayGoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.migrateTo != null) this.migrateTo = err.migrateTo;

    this.name = "MppPayGoneError";
  }
}

/** @internal */
export const MppPayGoneError$inboundSchema: z.ZodMiniType<
  MppPayGoneError,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(types.string()),
    migrate_to: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "migrate_to": "migrateTo",
    });

    return new MppPayGoneError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
