/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as types from "../../types/primitives.js";
import { Mag3ntError } from "./mag3nt-error.js";

/**
 * Pay link has been used
 */
export type GoneErrorData = {
  status?: string | undefined;
  error?: string | undefined;
};

/**
 * Pay link has been used
 */
export class GoneError extends Mag3ntError {
  status?: string | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GoneErrorData;

  constructor(
    err: GoneErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.status != null) this.status = err.status;
    if (err.error != null) this.error = err.error;

    this.name = "GoneError";
  }
}

/** @internal */
export const GoneError$inboundSchema: z.ZodMiniType<GoneError, unknown> = z
  .pipe(
    z.object({
      status: types.optional(types.string()),
      error: types.optional(types.string()),
      request$: z.custom<Request>(x => x instanceof Request),
      response$: z.custom<Response>(x => x instanceof Response),
      body$: z.string(),
    }),
    z.transform((v) => {
      return new GoneError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    }),
  );
