/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as operations from "../operations/index.js";
import { Mag3ntError } from "./mag3nt-error.js";

/**
 * Insufficient balance
 */
export type ForbiddenErrorData = {
  error?: string | undefined;
  available?: operations.WithdrawalsCreateAvailable | undefined;
  requested?: operations.Requested | undefined;
  withdrawalFee?: operations.ForbiddenWithdrawalFee | undefined;
};

/**
 * Insufficient balance
 */
export class ForbiddenError extends Mag3ntError {
  error?: string | undefined;
  available?: operations.WithdrawalsCreateAvailable | undefined;
  requested?: operations.Requested | undefined;
  withdrawalFee?: operations.ForbiddenWithdrawalFee | undefined;

  /** The original data that was passed to this error instance. */
  data$: ForbiddenErrorData;

  constructor(
    err: ForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.available != null) this.available = err.available;
    if (err.requested != null) this.requested = err.requested;
    if (err.withdrawalFee != null) this.withdrawalFee = err.withdrawalFee;

    this.name = "ForbiddenError";
  }
}

/**
 * Missing fields or amount too small to cover fee
 */
export type BadRequestErrorData = {
  error?: string | undefined;
  withdrawalFee?: operations.BadRequestWithdrawalFee | undefined;
  minimumWithdrawal?: operations.MinimumWithdrawal | undefined;
  network?: string | undefined;
};

/**
 * Missing fields or amount too small to cover fee
 */
export class BadRequestError extends Mag3ntError {
  error?: string | undefined;
  withdrawalFee?: operations.BadRequestWithdrawalFee | undefined;
  minimumWithdrawal?: operations.MinimumWithdrawal | undefined;
  network?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: BadRequestErrorData;

  constructor(
    err: BadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.withdrawalFee != null) this.withdrawalFee = err.withdrawalFee;
    if (err.minimumWithdrawal != null) {
      this.minimumWithdrawal = err.minimumWithdrawal;
    }
    if (err.network != null) this.network = err.network;

    this.name = "BadRequestError";
  }
}

/** @internal */
export const ForbiddenError$inboundSchema: z.ZodMiniType<
  ForbiddenError,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(types.string()),
    available: types.optional(
      z.lazy(() => operations.WithdrawalsCreateAvailable$inboundSchema),
    ),
    requested: types.optional(z.lazy(() => operations.Requested$inboundSchema)),
    withdrawal_fee: types.optional(
      z.lazy(() => operations.ForbiddenWithdrawalFee$inboundSchema),
    ),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "withdrawal_fee": "withdrawalFee",
    });

    return new ForbiddenError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);

/** @internal */
export const BadRequestError$inboundSchema: z.ZodMiniType<
  BadRequestError,
  unknown
> = z.pipe(
  z.object({
    error: types.optional(types.string()),
    withdrawal_fee: types.optional(
      z.lazy(() => operations.BadRequestWithdrawalFee$inboundSchema),
    ),
    minimum_withdrawal: types.optional(
      z.lazy(() => operations.MinimumWithdrawal$inboundSchema),
    ),
    network: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "withdrawal_fee": "withdrawalFee",
      "minimum_withdrawal": "minimumWithdrawal",
    });

    return new BadRequestError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
