/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ap2Ap2CreateMandate } from "../funcs/ap2-ap2-create-mandate.js";
import { ap2Ap2Execute } from "../funcs/ap2-ap2-execute.js";
import { ap2Ap2GetAgentCard } from "../funcs/ap2-ap2-get-agent-card.js";
import { ap2Ap2ListMandates } from "../funcs/ap2-ap2-list-mandates.js";
import { ap2Ap2ListPaymentMethods } from "../funcs/ap2-ap2-list-payment-methods.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Ap2 extends ClientSDK {
  /**
   * Get the default agent card for AP2 payments
   */
  async ap2GetAgentCard(
    options?: RequestOptions,
  ): Promise<operations.Ap2GetAgentCardResponse> {
    return unwrapAsync(ap2Ap2GetAgentCard(
      this,
      options,
    ));
  }

  /**
   * List available payment methods for AP2
   */
  async ap2ListPaymentMethods(
    options?: RequestOptions,
  ): Promise<operations.Ap2ListPaymentMethodsResponse> {
    return unwrapAsync(ap2Ap2ListPaymentMethods(
      this,
      options,
    ));
  }

  /**
   * Create a spending mandate for recurring AP2 payments
   */
  async ap2CreateMandate(
    request: operations.Ap2CreateMandateRequest,
    options?: RequestOptions,
  ): Promise<operations.Ap2CreateMandateResponse> {
    return unwrapAsync(ap2Ap2CreateMandate(
      this,
      request,
      options,
    ));
  }

  /**
   * Execute a payment against an AP2 mandate
   */
  async ap2Execute(
    request: operations.Ap2ExecuteRequest,
    options?: RequestOptions,
  ): Promise<operations.Ap2ExecuteResponse> {
    return unwrapAsync(ap2Ap2Execute(
      this,
      request,
      options,
    ));
  }

  /**
   * List mandates for a card
   */
  async ap2ListMandates(
    cardId: string,
    options?: RequestOptions,
  ): Promise<operations.Ap2ListMandatesResponse> {
    return unwrapAsync(ap2Ap2ListMandates(
      this,
      cardId,
      options,
    ));
  }
}
