/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { cardsCardsBulkCreate } from "../funcs/cards-cards-bulk-create.js";
import { cardsCardsClaim } from "../funcs/cards-cards-claim.js";
import { cardsCardsCreate } from "../funcs/cards-cards-create.js";
import { cardsCardsFreeze } from "../funcs/cards-cards-freeze.js";
import { cardsCardsListTransactions } from "../funcs/cards-cards-list-transactions.js";
import { cardsCardsList } from "../funcs/cards-cards-list.js";
import { cardsCardsUnfreeze } from "../funcs/cards-cards-unfreeze.js";
import { cardsCardsUpdateControls } from "../funcs/cards-cards-update-controls.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Cards extends ClientSDK {
  /**
   * List all cards for the authenticated wallet
   */
  async cardsList(
    options?: RequestOptions,
  ): Promise<operations.CardsListResponse> {
    return unwrapAsync(cardsCardsList(
      this,
      options,
    ));
  }

  /**
   * Issue a new virtual payment card
   *
   * @remarks
   * Creates a card backed by your treasury balance. Provide `tx_hash` for UI pay-and-issue flow (card starts as PENDING_FUNDING). Omit `tx_hash` to allocate from pre-funded balance.
   */
  async cardsCreate(
    request: operations.CardsCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.CardsCreateResponse> {
    return unwrapAsync(cardsCardsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Issue multiple cards in a single atomic request
   *
   * @remarks
   * Creates up to 1000 cards atomically. All cards are allocated from treasury balance in a single atomic operation. Supports idempotency via header.
   */
  async cardsBulkCreate(
    body: operations.CardsBulkCreateRequestBody,
    idempotencyKey?: string | undefined,
    options?: RequestOptions,
  ): Promise<operations.CardsBulkCreateResponse> {
    return unwrapAsync(cardsCardsBulkCreate(
      this,
      body,
      idempotencyKey,
      options,
    ));
  }

  /**
   * Freeze a card to block all transactions
   */
  async cardsFreeze(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.CardsFreezeResponse> {
    return unwrapAsync(cardsCardsFreeze(
      this,
      id,
      options,
    ));
  }

  /**
   * Unfreeze a previously frozen card
   */
  async cardsUnfreeze(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.CardsUnfreezeResponse> {
    return unwrapAsync(cardsCardsUnfreeze(
      this,
      id,
      options,
    ));
  }

  /**
   * Claim a card using its token
   */
  async cardsClaim(
    id: string,
    body: operations.CardsClaimRequestBody,
    options?: RequestOptions,
  ): Promise<components.Card> {
    return unwrapAsync(cardsCardsClaim(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Update card spending controls
   */
  async cardsUpdateControls(
    id: string,
    body: operations.CardsUpdateControlsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CardsUpdateControlsResponse> {
    return unwrapAsync(cardsCardsUpdateControls(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * List transactions for a card
   */
  async cardsListTransactions(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.CardsListTransactionsResponse> {
    return unwrapAsync(cardsCardsListTransactions(
      this,
      id,
      options,
    ));
  }
}
