/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fundingFundingGetBalance } from "../funcs/funding-funding-get-balance.js";
import { fundingFundingListTokens } from "../funcs/funding-funding-list-tokens.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Funding extends ClientSDK {
  /**
   * List accepted tokens per network
   */
  async fundingListTokens(
    options?: RequestOptions,
  ): Promise<operations.FundingListTokensResponse> {
    return unwrapAsync(fundingFundingListTokens(
      this,
      options,
    ));
  }

  /**
   * Get treasury balance for authenticated wallet
   */
  async fundingGetBalance(
    options?: RequestOptions,
  ): Promise<operations.FundingGetBalanceResponse> {
    return unwrapAsync(fundingFundingGetBalance(
      this,
      options,
    ));
  }
}
