/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { keysKeysCreate } from "../funcs/keys-keys-create.js";
import { keysKeysList } from "../funcs/keys-keys-list.js";
import { keysKeysRevoke } from "../funcs/keys-keys-revoke.js";
import { keysKeysValidate } from "../funcs/keys-keys-validate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Keys extends ClientSDK {
  /**
   * Generate a new API key
   *
   * @remarks
   * Returns the raw key once. Store it securely — it cannot be retrieved again.
   */
  async keysCreate(
    options?: RequestOptions,
  ): Promise<operations.KeysCreateResponse> {
    return unwrapAsync(keysKeysCreate(
      this,
      options,
    ));
  }

  /**
   * List all API keys for the authenticated wallet
   */
  async keysList(
    options?: RequestOptions,
  ): Promise<operations.KeysListResponse> {
    return unwrapAsync(keysKeysList(
      this,
      options,
    ));
  }

  /**
   * Revoke an API key
   */
  async keysRevoke(
    hash: string,
    options?: RequestOptions,
  ): Promise<operations.KeysRevokeResponse> {
    return unwrapAsync(keysKeysRevoke(
      this,
      hash,
      options,
    ));
  }

  /**
   * Validate an API key
   */
  async keysValidate(
    options?: RequestOptions,
  ): Promise<operations.KeysValidateResponse> {
    return unwrapAsync(keysKeysValidate(
      this,
      options,
    ));
  }
}
