/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { mppMPPCreateSession } from "../funcs/mpp-mpp-create-session.js";
import { mppMPPDiscover } from "../funcs/mpp-mpp-discover.js";
import { mppMPPPay } from "../funcs/mpp-mpp-pay.js";
import { mppMPPReceive } from "../funcs/mpp-mpp-receive.js";
import { mppMPPStreamsClose } from "../funcs/mpp-mpp-streams-close.js";
import { mppMPPStreamsGet } from "../funcs/mpp-mpp-streams-get.js";
import { mppMPPStreamsOpen } from "../funcs/mpp-mpp-streams-open.js";
import { mppMPPStreamsTick } from "../funcs/mpp-mpp-streams-tick.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Mpp extends ClientSDK {
  /**
   * Make a micropayment via MPP protocol
   */
  async mppPay(
    request: operations.MppPayRequest,
    options?: RequestOptions,
  ): Promise<operations.MppPayResponse> {
    return unwrapAsync(mppMPPPay(
      this,
      request,
      options,
    ));
  }

  /**
   * Create an MPP payment session
   */
  async mppCreateSession(
    request: operations.MppCreateSessionRequest,
    options?: RequestOptions,
  ): Promise<operations.MppCreateSessionResponse> {
    return unwrapAsync(mppMPPCreateSession(
      this,
      request,
      options,
    ));
  }

  /**
   * Discover MPP capabilities for a URL
   */
  async mppDiscover(
    url: string,
    options?: RequestOptions,
  ): Promise<operations.MppDiscoverResponse> {
    return unwrapAsync(mppMPPDiscover(
      this,
      url,
      options,
    ));
  }

  /**
   * Verify and accept an MPP payment
   */
  async mppReceive(
    request: operations.MppReceiveRequest,
    options?: RequestOptions,
  ): Promise<operations.MppReceiveResponse> {
    return unwrapAsync(mppMPPReceive(
      this,
      request,
      options,
    ));
  }

  /**
   * Open a payment stream for continuous micropayments
   */
  async mppStreamsOpen(
    request: operations.MppStreamsOpenRequest,
    options?: RequestOptions,
  ): Promise<operations.MppStreamsOpenResponse> {
    return unwrapAsync(mppMPPStreamsOpen(
      this,
      request,
      options,
    ));
  }

  /**
   * Advance a payment stream by one tick
   */
  async mppStreamsTick(
    request: operations.MppStreamsTickRequest,
    options?: RequestOptions,
  ): Promise<operations.MppStreamsTickResponse> {
    return unwrapAsync(mppMPPStreamsTick(
      this,
      request,
      options,
    ));
  }

  /**
   * Close a payment stream
   */
  async mppStreamsClose(
    request: operations.MppStreamsCloseRequest,
    options?: RequestOptions,
  ): Promise<operations.MppStreamsCloseResponse> {
    return unwrapAsync(mppMPPStreamsClose(
      this,
      request,
      options,
    ));
  }

  /**
   * Get payment stream details
   */
  async mppStreamsGet(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.MppStreamsGetResponse> {
    return unwrapAsync(mppMPPStreamsGet(
      this,
      id,
      options,
    ));
  }
}
