/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { payLinksPayLinksCancel } from "../funcs/pay-links-pay-links-cancel.js";
import { payLinksPayLinksCreate } from "../funcs/pay-links-pay-links-create.js";
import { payLinksPayLinksGetStatus } from "../funcs/pay-links-pay-links-get-status.js";
import { payLinksPayLinksGet } from "../funcs/pay-links-pay-links-get.js";
import { payLinksPayLinksList } from "../funcs/pay-links-pay-links-list.js";
import { payLinksPayLinksPrepare } from "../funcs/pay-links-pay-links-prepare.js";
import { payLinksPayLinksResolve } from "../funcs/pay-links-pay-links-resolve.js";
import { payLinksPayLinksSettle } from "../funcs/pay-links-pay-links-settle.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PayLinks extends ClientSDK {
  /**
   * Create a shareable payment link
   */
  async payLinksCreate(
    request: operations.PayLinksCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.PayLinksCreateResponse> {
    return unwrapAsync(payLinksPayLinksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List pay links for authenticated wallet
   */
  async payLinksList(
    options?: RequestOptions,
  ): Promise<operations.PayLinksListResponse> {
    return unwrapAsync(payLinksPayLinksList(
      this,
      options,
    ));
  }

  /**
   * Get public pay link details
   */
  async payLinksGet(
    code: string,
    options?: RequestOptions,
  ): Promise<components.PayLink> {
    return unwrapAsync(payLinksPayLinksGet(
      this,
      code,
      options,
    ));
  }

  /**
   * Cancel a pay link
   */
  async payLinksCancel(
    code: string,
    options?: RequestOptions,
  ): Promise<operations.PayLinksCancelResponse> {
    return unwrapAsync(payLinksPayLinksCancel(
      this,
      code,
      options,
    ));
  }

  /**
   * Check pay link payment status
   */
  async payLinksGetStatus(
    code: string,
    options?: RequestOptions,
  ): Promise<operations.PayLinksGetStatusResponse> {
    return unwrapAsync(payLinksPayLinksGetStatus(
      this,
      code,
      options,
    ));
  }

  /**
   * Resolve a pay link for payment processing
   */
  async payLinksResolve(
    code: string,
    options?: RequestOptions,
  ): Promise<operations.PayLinksResolveResponse> {
    return unwrapAsync(payLinksPayLinksResolve(
      this,
      code,
      options,
    ));
  }

  /**
   * Prepare payment intent for a pay link
   */
  async payLinksPrepare(
    code: string,
    options?: RequestOptions,
  ): Promise<operations.PayLinksPrepareResponse> {
    return unwrapAsync(payLinksPayLinksPrepare(
      this,
      code,
      options,
    ));
  }

  /**
   * Settle a pay link payment
   */
  async payLinksSettle(
    code: string,
    body: operations.PayLinksSettleRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PayLinksSettleResponse> {
    return unwrapAsync(payLinksPayLinksSettle(
      this,
      code,
      body,
      options,
    ));
  }
}
