/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsPaymentsExecute } from "../funcs/payments-payments-execute.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * Execute a universal outbound payment
   *
   * @remarks
   * Enables any mag3nt card to pay any external x402, MPP, or AP2 endpoint in a single HTTP call. The engine automatically probes the target URL, detects the protocol, and settles on-chain.
   */
  async paymentsExecute(
    request: operations.PaymentsExecuteRequest,
    options?: RequestOptions,
  ): Promise<operations.PaymentsExecuteResponse> {
    return unwrapAsync(paymentsPaymentsExecute(
      this,
      request,
      options,
    ));
  }
}
