/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { validateWebhook } from "../funcs/validate-webhook.js";
import { ClientSDK } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Ap2 } from "./ap2.js";
import { Cards } from "./cards.js";
import { Funding } from "./funding.js";
import { Keys } from "./keys.js";
import { Mpp } from "./mpp.js";
import { PayLinks } from "./pay-links.js";
import { Payments } from "./payments.js";
import { Settlement } from "./settlement.js";
import { Status } from "./status.js";
import { Webhooks } from "./webhooks.js";
import { Withdrawals } from "./withdrawals.js";
import { X402 } from "./x402.js";

export class Mag3nt extends ClientSDK {
  private _cards?: Cards;
  get cards(): Cards {
    return (this._cards ??= new Cards(this._options));
  }

  private _keys?: Keys;
  get keys(): Keys {
    return (this._keys ??= new Keys(this._options));
  }

  private _funding?: Funding;
  get funding(): Funding {
    return (this._funding ??= new Funding(this._options));
  }

  private _withdrawals?: Withdrawals;
  get withdrawals(): Withdrawals {
    return (this._withdrawals ??= new Withdrawals(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _x402?: X402;
  get x402(): X402 {
    return (this._x402 ??= new X402(this._options));
  }

  private _status?: Status;
  get status(): Status {
    return (this._status ??= new Status(this._options));
  }

  private _ap2?: Ap2;
  get ap2(): Ap2 {
    return (this._ap2 ??= new Ap2(this._options));
  }

  private _mpp?: Mpp;
  get mpp(): Mpp {
    return (this._mpp ??= new Mpp(this._options));
  }

  private _payLinks?: PayLinks;
  get payLinks(): PayLinks {
    return (this._payLinks ??= new PayLinks(this._options));
  }

  private _settlement?: Settlement;
  get settlement(): Settlement {
    return (this._settlement ??= new Settlement(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  async validateWebhook({
    request,
  }: {
    request: {
      body: string;
      headers: Record<string, string> | Headers;
      url: string;
      method: string;
    } | Request;
  }): Promise<components.PaymentSettledEvent> {
    return unwrapAsync(validateWebhook(
      this,
      { request },
    ));
  }
}
