/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { settlementSettlementGetStatus } from "../funcs/settlement-settlement-get-status.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Settlement extends ClientSDK {
  /**
   * Check settlement status for a transaction
   */
  async settlementGetStatus(
    txnId: string,
    options?: RequestOptions,
  ): Promise<operations.SettlementGetStatusResponse> {
    return unwrapAsync(settlementSettlementGetStatus(
      this,
      txnId,
      options,
    ));
  }
}
