/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statusStatusGetConfig } from "../funcs/status-status-get-config.js";
import { statusStatusGet } from "../funcs/status-status-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Status extends ClientSDK {
  /**
   * Get platform status, supported protocols, and capabilities
   */
  async statusGet(
    options?: RequestOptions,
  ): Promise<operations.StatusGetResponse> {
    return unwrapAsync(statusStatusGet(
      this,
      options,
    ));
  }

  /**
   * Get treasury addresses and token registry
   */
  async statusGetConfig(
    options?: RequestOptions,
  ): Promise<operations.StatusGetConfigResponse> {
    return unwrapAsync(statusStatusGetConfig(
      this,
      options,
    ));
  }
}
