/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksWebhooksCreate } from "../funcs/webhooks-webhooks-create.js";
import { webhooksWebhooksDelete } from "../funcs/webhooks-webhooks-delete.js";
import { webhooksWebhooksList } from "../funcs/webhooks-webhooks-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Register a webhook endpoint
   *
   * @remarks
   * Register an HTTPS endpoint to receive signed `payment.settled` events when your pay links settle. The signing secret is returned ONCE in this response and cannot be retrieved again. Use it to verify the X-mag3nt-Signature header on each delivery. Max 5 active webhooks per wallet. URLs must be https and may not target private/loopback hosts.
   */
  async webhooksCreate(
    request: operations.WebhooksCreateRequest,
    options?: RequestOptions,
  ): Promise<components.WebhookSecret> {
    return unwrapAsync(webhooksWebhooksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List registered webhooks
   *
   * @remarks
   * Returns all webhooks for the authenticated wallet. Secrets are never returned.
   */
  async webhooksList(
    options?: RequestOptions,
  ): Promise<operations.WebhooksListResponse> {
    return unwrapAsync(webhooksWebhooksList(
      this,
      options,
    ));
  }

  /**
   * Delete a webhook endpoint
   */
  async webhooksDelete(
    id: string,
    options?: RequestOptions,
  ): Promise<operations.WebhooksDeleteResponse> {
    return unwrapAsync(webhooksWebhooksDelete(
      this,
      id,
      options,
    ));
  }
}
