/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { withdrawalsWithdrawalsCreate } from "../funcs/withdrawals-withdrawals-create.js";
import { withdrawalsWithdrawalsList } from "../funcs/withdrawals-withdrawals-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Withdrawals extends ClientSDK {
  /**
   * Withdraw unspent funds back to your wallet
   *
   * @remarks
   * Initiates a withdrawal of USDC from your treasury balance to an on-chain wallet address. A flat network fee is deducted from the requested amount. The net amount is sent on-chain via CDP; the fee is retained as platform revenue. Withdrawals are processed asynchronously: check status via GET /api/withdrawals.
   */
  async withdrawalsCreate(
    request: operations.WithdrawalsCreateRequest,
    options?: RequestOptions,
  ): Promise<operations.WithdrawalsCreateResponse> {
    return unwrapAsync(withdrawalsWithdrawalsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List withdrawal history
   *
   * @remarks
   * Returns up to 50 most recent withdrawals for the authenticated wallet.
   */
  async withdrawalsList(
    id?: string | undefined,
    status?: operations.WithdrawalsListStatus | undefined,
    options?: RequestOptions,
  ): Promise<operations.WithdrawalsListResponse> {
    return unwrapAsync(withdrawalsWithdrawalsList(
      this,
      id,
      status,
      options,
    ));
  }
}
