/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { x402X402Discover } from "../funcs/x402-x402-discover.js";
import { x402X402Pay } from "../funcs/x402-x402-pay.js";
import { x402X402Receive } from "../funcs/x402-x402-receive.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class X402 extends ClientSDK {
  /**
   * Pay for a service via x402 protocol
   *
   * @remarks
   * Authorizes a payment against a funded card. The card must be ACTIVE with sufficient allocation. Returns payment headers the agent can attach to retry the original 402 request.
   */
  async x402Pay(
    request: operations.X402PayRequest,
    options?: RequestOptions,
  ): Promise<operations.X402PayResponse> {
    return unwrapAsync(x402X402Pay(
      this,
      request,
      options,
    ));
  }

  /**
   * Discover x402 payment requirements for a URL
   */
  async x402Discover(
    url: string,
    options?: RequestOptions,
  ): Promise<operations.X402DiscoverResponse> {
    return unwrapAsync(x402X402Discover(
      this,
      url,
      options,
    ));
  }

  /**
   * Verify and accept an x402 payment
   */
  async x402Receive(
    request: operations.X402ReceiveRequest,
    options?: RequestOptions,
  ): Promise<operations.X402ReceiveResponse> {
    return unwrapAsync(x402X402Receive(
      this,
      request,
      options,
    ));
  }
}
