/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @mag3nt/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx cardsCardsList.example.ts
 */

import { Mag3nt } from "@mag3nt/sdk";

const mag3nt = new Mag3nt({
  apiKeyAuth: "<YOUR_API_KEY_HERE>",
});

async function main() {
  const result = await mag3nt.cards.cardsList();

  console.log(result);
}

main().catch(console.error);
