/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Ap2ListMandatesRequest = {
  cardId: string;
};

export type Ap2ListMandatesAmount = number | string;

export type Mandate = {
  mandateId?: string | undefined;
  merchant?: string | undefined;
  amount?: number | string | undefined;
  status?: string | undefined;
};

/**
 * Mandates list
 */
export type Ap2ListMandatesResponse = {
  mandates?: Array<Mandate> | undefined;
};

/** @internal */
export type Ap2ListMandatesRequest$Outbound = {
  card_id: string;
};

/** @internal */
export const Ap2ListMandatesRequest$outboundSchema: z.ZodMiniType<
  Ap2ListMandatesRequest$Outbound,
  Ap2ListMandatesRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
    });
  }),
);

export function ap2ListMandatesRequestToJSON(
  ap2ListMandatesRequest: Ap2ListMandatesRequest,
): string {
  return JSON.stringify(
    Ap2ListMandatesRequest$outboundSchema.parse(ap2ListMandatesRequest),
  );
}

/** @internal */
export const Ap2ListMandatesAmount$inboundSchema: z.ZodMiniType<
  Ap2ListMandatesAmount,
  unknown
> = smartUnion([types.number(), types.string()]);

export function ap2ListMandatesAmountFromJSON(
  jsonString: string,
): SafeParseResult<Ap2ListMandatesAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2ListMandatesAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2ListMandatesAmount' from JSON`,
  );
}

/** @internal */
export const Mandate$inboundSchema: z.ZodMiniType<Mandate, unknown> = z.pipe(
  z.object({
    mandate_id: types.optional(types.string()),
    merchant: types.optional(types.string()),
    amount: types.optional(smartUnion([types.number(), types.string()])),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mandate_id": "mandateId",
    });
  }),
);

export function mandateFromJSON(
  jsonString: string,
): SafeParseResult<Mandate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mandate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mandate' from JSON`,
  );
}

/** @internal */
export const Ap2ListMandatesResponse$inboundSchema: z.ZodMiniType<
  Ap2ListMandatesResponse,
  unknown
> = z.object({
  mandates: types.optional(z.array(z.lazy(() => Mandate$inboundSchema))),
});

export function ap2ListMandatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2ListMandatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2ListMandatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2ListMandatesResponse' from JSON`,
  );
}
