/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Ap2SettleAmount = number | string;

export type Ap2SettleRequest = {
  payerCardId: string;
  payerCardToken: string;
  receiverCardId: string;
  amount: number | string;
  network?: string | undefined;
};

/**
 * Settlement complete
 */
export type Ap2SettleResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
};

/** @internal */
export type Ap2SettleAmount$Outbound = number | string;

/** @internal */
export const Ap2SettleAmount$outboundSchema: z.ZodMiniType<
  Ap2SettleAmount$Outbound,
  Ap2SettleAmount
> = smartUnion([z.number(), z.string()]);

export function ap2SettleAmountToJSON(
  ap2SettleAmount: Ap2SettleAmount,
): string {
  return JSON.stringify(Ap2SettleAmount$outboundSchema.parse(ap2SettleAmount));
}

/** @internal */
export type Ap2SettleRequest$Outbound = {
  payer_card_id: string;
  payer_card_token: string;
  receiver_card_id: string;
  amount: number | string;
  network: string;
};

/** @internal */
export const Ap2SettleRequest$outboundSchema: z.ZodMiniType<
  Ap2SettleRequest$Outbound,
  Ap2SettleRequest
> = z.pipe(
  z.object({
    payerCardId: z.string(),
    payerCardToken: z.string(),
    receiverCardId: z.string(),
    amount: smartUnion([z.number(), z.string()]),
    network: z._default(z.string(), "eip155:8453"),
  }),
  z.transform((v) => {
    return remap$(v, {
      payerCardId: "payer_card_id",
      payerCardToken: "payer_card_token",
      receiverCardId: "receiver_card_id",
    });
  }),
);

export function ap2SettleRequestToJSON(
  ap2SettleRequest: Ap2SettleRequest,
): string {
  return JSON.stringify(
    Ap2SettleRequest$outboundSchema.parse(ap2SettleRequest),
  );
}

/** @internal */
export const Ap2SettleResponse$inboundSchema: z.ZodMiniType<
  Ap2SettleResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
    });
  }),
);

export function ap2SettleResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2SettleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2SettleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2SettleResponse' from JSON`,
  );
}
