/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Ap2CreateMandateRequest = {
  cardId: string;
  cardToken: string;
  amount: number;
  merchant: string;
  maxAmount?: number | undefined;
  expiresAt?: Date | undefined;
};

/**
 * Mandate created
 */
export type Ap2CreateMandateResponse = {
  mandateId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export type Ap2CreateMandateRequest$Outbound = {
  card_id: string;
  card_token: string;
  amount: number;
  merchant: string;
  max_amount?: number | undefined;
  expires_at?: string | undefined;
};

/** @internal */
export const Ap2CreateMandateRequest$outboundSchema: z.ZodMiniType<
  Ap2CreateMandateRequest$Outbound,
  Ap2CreateMandateRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    amount: z.number(),
    merchant: z.string(),
    maxAmount: z.optional(z.number()),
    expiresAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
      maxAmount: "max_amount",
      expiresAt: "expires_at",
    });
  }),
);

export function ap2CreateMandateRequestToJSON(
  ap2CreateMandateRequest: Ap2CreateMandateRequest,
): string {
  return JSON.stringify(
    Ap2CreateMandateRequest$outboundSchema.parse(ap2CreateMandateRequest),
  );
}

/** @internal */
export const Ap2CreateMandateResponse$inboundSchema: z.ZodMiniType<
  Ap2CreateMandateResponse,
  unknown
> = z.pipe(
  z.object({
    mandate_id: types.optional(types.string()),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mandate_id": "mandateId",
    });
  }),
);

export function ap2CreateMandateResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2CreateMandateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2CreateMandateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2CreateMandateResponse' from JSON`,
  );
}
