/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Agent card
 */
export type Ap2GetAgentCardResponse = {
  agentCard?: components.Card | undefined;
};

/** @internal */
export const Ap2GetAgentCardResponse$inboundSchema: z.ZodMiniType<
  Ap2GetAgentCardResponse,
  unknown
> = z.pipe(
  z.object({
    agent_card: types.optional(components.Card$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "agent_card": "agentCard",
    });
  }),
);

export function ap2GetAgentCardResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2GetAgentCardResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2GetAgentCardResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2GetAgentCardResponse' from JSON`,
  );
}
