/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Ap2ExecuteRequest = {
  cardId: string;
  cardToken: string;
  amount: number;
  mandateId?: string | undefined;
};

/**
 * Payment executed
 */
export type Ap2ExecuteResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
};

/** @internal */
export type Ap2ExecuteRequest$Outbound = {
  card_id: string;
  card_token: string;
  amount: number;
  mandate_id?: string | undefined;
};

/** @internal */
export const Ap2ExecuteRequest$outboundSchema: z.ZodMiniType<
  Ap2ExecuteRequest$Outbound,
  Ap2ExecuteRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    amount: z.number(),
    mandateId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
      mandateId: "mandate_id",
    });
  }),
);

export function ap2ExecuteRequestToJSON(
  ap2ExecuteRequest: Ap2ExecuteRequest,
): string {
  return JSON.stringify(
    Ap2ExecuteRequest$outboundSchema.parse(ap2ExecuteRequest),
  );
}

/** @internal */
export const Ap2ExecuteResponse$inboundSchema: z.ZodMiniType<
  Ap2ExecuteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
    });
  }),
);

export function ap2ExecuteResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2ExecuteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2ExecuteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2ExecuteResponse' from JSON`,
  );
}
