/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Method = {
  type?: string | undefined;
  cardId?: string | undefined;
  available?: number | undefined;
};

/**
 * Payment methods
 */
export type Ap2ListPaymentMethodsResponse = {
  methods?: Array<Method> | undefined;
};

/** @internal */
export const Method$inboundSchema: z.ZodMiniType<Method, unknown> = z.pipe(
  z.object({
    type: types.optional(types.string()),
    card_id: types.optional(types.string()),
    available: types.optional(types.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
    });
  }),
);

export function methodFromJSON(
  jsonString: string,
): SafeParseResult<Method, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Method$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Method' from JSON`,
  );
}

/** @internal */
export const Ap2ListPaymentMethodsResponse$inboundSchema: z.ZodMiniType<
  Ap2ListPaymentMethodsResponse,
  unknown
> = z.object({
  methods: types.optional(z.array(z.lazy(() => Method$inboundSchema))),
});

export function ap2ListPaymentMethodsResponseFromJSON(
  jsonString: string,
): SafeParseResult<Ap2ListPaymentMethodsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2ListPaymentMethodsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2ListPaymentMethodsResponse' from JSON`,
  );
}
