/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CardsFreezeRequest = {
  id: string;
};

/**
 * Card frozen
 */
export type CardsFreezeResponse = {
  success?: boolean | undefined;
  cardId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export type CardsFreezeRequest$Outbound = {
  id: string;
};

/** @internal */
export const CardsFreezeRequest$outboundSchema: z.ZodMiniType<
  CardsFreezeRequest$Outbound,
  CardsFreezeRequest
> = z.object({
  id: z.string(),
});

export function cardsFreezeRequestToJSON(
  cardsFreezeRequest: CardsFreezeRequest,
): string {
  return JSON.stringify(
    CardsFreezeRequest$outboundSchema.parse(cardsFreezeRequest),
  );
}

/** @internal */
export const CardsFreezeResponse$inboundSchema: z.ZodMiniType<
  CardsFreezeResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    card_id: types.optional(types.string()),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
    });
  }),
);

export function cardsFreezeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsFreezeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsFreezeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsFreezeResponse' from JSON`,
  );
}
