/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Amount in USDC to add
 */
export type CardsTopUpAmount = number | string;

export type CardsTopUpRequestBody = {
  /**
   * Amount in USDC to add
   */
  amount: number | string;
};

export type CardsTopUpRequest = {
  id: string;
  body: CardsTopUpRequestBody;
};

export type Added = number | string;

export type NewLimit = number | string;

/**
 * Card topped up
 */
export type CardsTopUpResponse = {
  success?: boolean | undefined;
  cardId?: string | undefined;
  added?: number | string | undefined;
  newLimit?: number | string | undefined;
};

/** @internal */
export type CardsTopUpAmount$Outbound = number | string;

/** @internal */
export const CardsTopUpAmount$outboundSchema: z.ZodMiniType<
  CardsTopUpAmount$Outbound,
  CardsTopUpAmount
> = smartUnion([z.number(), z.string()]);

export function cardsTopUpAmountToJSON(
  cardsTopUpAmount: CardsTopUpAmount,
): string {
  return JSON.stringify(
    CardsTopUpAmount$outboundSchema.parse(cardsTopUpAmount),
  );
}

/** @internal */
export type CardsTopUpRequestBody$Outbound = {
  amount: number | string;
};

/** @internal */
export const CardsTopUpRequestBody$outboundSchema: z.ZodMiniType<
  CardsTopUpRequestBody$Outbound,
  CardsTopUpRequestBody
> = z.object({
  amount: smartUnion([z.number(), z.string()]),
});

export function cardsTopUpRequestBodyToJSON(
  cardsTopUpRequestBody: CardsTopUpRequestBody,
): string {
  return JSON.stringify(
    CardsTopUpRequestBody$outboundSchema.parse(cardsTopUpRequestBody),
  );
}

/** @internal */
export type CardsTopUpRequest$Outbound = {
  id: string;
  body: CardsTopUpRequestBody$Outbound;
};

/** @internal */
export const CardsTopUpRequest$outboundSchema: z.ZodMiniType<
  CardsTopUpRequest$Outbound,
  CardsTopUpRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => CardsTopUpRequestBody$outboundSchema),
});

export function cardsTopUpRequestToJSON(
  cardsTopUpRequest: CardsTopUpRequest,
): string {
  return JSON.stringify(
    CardsTopUpRequest$outboundSchema.parse(cardsTopUpRequest),
  );
}

/** @internal */
export const Added$inboundSchema: z.ZodMiniType<Added, unknown> = smartUnion([
  types.number(),
  types.string(),
]);

export function addedFromJSON(
  jsonString: string,
): SafeParseResult<Added, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Added$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Added' from JSON`,
  );
}

/** @internal */
export const NewLimit$inboundSchema: z.ZodMiniType<NewLimit, unknown> =
  smartUnion([types.number(), types.string()]);

export function newLimitFromJSON(
  jsonString: string,
): SafeParseResult<NewLimit, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NewLimit$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NewLimit' from JSON`,
  );
}

/** @internal */
export const CardsTopUpResponse$inboundSchema: z.ZodMiniType<
  CardsTopUpResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    card_id: types.optional(types.string()),
    added: types.optional(smartUnion([types.number(), types.string()])),
    new_limit: types.optional(smartUnion([types.number(), types.string()])),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
      "new_limit": "newLimit",
    });
  }),
);

export function cardsTopUpResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsTopUpResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsTopUpResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsTopUpResponse' from JSON`,
  );
}
