/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Maximum spend in USDC
 */
export type CardsCreateLimitAmount = number | string;

export type CardsCreateRequest = {
  /**
   * Human-readable label for the card
   */
  purpose: string;
  /**
   * Maximum spend in USDC
   */
  limitAmount: number | string;
  network?: string | undefined;
  asset?: string | undefined;
  /**
   * On-chain funding transaction hash (optional)
   */
  txHash?: string | undefined;
  /**
   * Comma-separated merchant category codes
   */
  mccLocks?: string | undefined;
  singleUse?: boolean | undefined;
  /**
   * Hours until expiry (0 = never)
   */
  expiresIn?: number | undefined;
};

/**
 * Card created
 */
export type CardsCreateResponse = {
  success?: boolean | undefined;
  card?: components.Card | undefined;
};

/** @internal */
export type CardsCreateLimitAmount$Outbound = number | string;

/** @internal */
export const CardsCreateLimitAmount$outboundSchema: z.ZodMiniType<
  CardsCreateLimitAmount$Outbound,
  CardsCreateLimitAmount
> = smartUnion([z.number(), z.string()]);

export function cardsCreateLimitAmountToJSON(
  cardsCreateLimitAmount: CardsCreateLimitAmount,
): string {
  return JSON.stringify(
    CardsCreateLimitAmount$outboundSchema.parse(cardsCreateLimitAmount),
  );
}

/** @internal */
export type CardsCreateRequest$Outbound = {
  purpose: string;
  limit_amount: number | string;
  network: string;
  asset: string;
  tx_hash?: string | undefined;
  mcc_locks?: string | undefined;
  single_use: boolean;
  expires_in?: number | undefined;
};

/** @internal */
export const CardsCreateRequest$outboundSchema: z.ZodMiniType<
  CardsCreateRequest$Outbound,
  CardsCreateRequest
> = z.pipe(
  z.object({
    purpose: z.string(),
    limitAmount: smartUnion([z.number(), z.string()]),
    network: z._default(z.string(), "eip155:8453"),
    asset: z._default(z.string(), "USDC"),
    txHash: z.optional(z.string()),
    mccLocks: z.optional(z.string()),
    singleUse: z._default(z.boolean(), false),
    expiresIn: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      limitAmount: "limit_amount",
      txHash: "tx_hash",
      mccLocks: "mcc_locks",
      singleUse: "single_use",
      expiresIn: "expires_in",
    });
  }),
);

export function cardsCreateRequestToJSON(
  cardsCreateRequest: CardsCreateRequest,
): string {
  return JSON.stringify(
    CardsCreateRequest$outboundSchema.parse(cardsCreateRequest),
  );
}

/** @internal */
export const CardsCreateResponse$inboundSchema: z.ZodMiniType<
  CardsCreateResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  card: types.optional(components.Card$inboundSchema),
});

export function cardsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsCreateResponse' from JSON`,
  );
}
