/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CardsUnfreezeRequest = {
  id: string;
};

/**
 * Card unfrozen
 */
export type CardsUnfreezeResponse = {
  success?: boolean | undefined;
  cardId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export type CardsUnfreezeRequest$Outbound = {
  id: string;
};

/** @internal */
export const CardsUnfreezeRequest$outboundSchema: z.ZodMiniType<
  CardsUnfreezeRequest$Outbound,
  CardsUnfreezeRequest
> = z.object({
  id: z.string(),
});

export function cardsUnfreezeRequestToJSON(
  cardsUnfreezeRequest: CardsUnfreezeRequest,
): string {
  return JSON.stringify(
    CardsUnfreezeRequest$outboundSchema.parse(cardsUnfreezeRequest),
  );
}

/** @internal */
export const CardsUnfreezeResponse$inboundSchema: z.ZodMiniType<
  CardsUnfreezeResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    card_id: types.optional(types.string()),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
    });
  }),
);

export function cardsUnfreezeResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsUnfreezeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsUnfreezeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsUnfreezeResponse' from JSON`,
  );
}
