/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CardsClaimRequestBody = {
  token: string;
};

export type CardsClaimRequest = {
  id: string;
  body: CardsClaimRequestBody;
};

/** @internal */
export type CardsClaimRequestBody$Outbound = {
  token: string;
};

/** @internal */
export const CardsClaimRequestBody$outboundSchema: z.ZodMiniType<
  CardsClaimRequestBody$Outbound,
  CardsClaimRequestBody
> = z.object({
  token: z.string(),
});

export function cardsClaimRequestBodyToJSON(
  cardsClaimRequestBody: CardsClaimRequestBody,
): string {
  return JSON.stringify(
    CardsClaimRequestBody$outboundSchema.parse(cardsClaimRequestBody),
  );
}

/** @internal */
export type CardsClaimRequest$Outbound = {
  id: string;
  body: CardsClaimRequestBody$Outbound;
};

/** @internal */
export const CardsClaimRequest$outboundSchema: z.ZodMiniType<
  CardsClaimRequest$Outbound,
  CardsClaimRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => CardsClaimRequestBody$outboundSchema),
});

export function cardsClaimRequestToJSON(
  cardsClaimRequest: CardsClaimRequest,
): string {
  return JSON.stringify(
    CardsClaimRequest$outboundSchema.parse(cardsClaimRequest),
  );
}
