/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CardsUpdateControlsRequestBody = {
  mccLocks?: string | undefined;
  dailyLimit?: number | undefined;
  maxTransaction?: number | undefined;
};

export type CardsUpdateControlsRequest = {
  id: string;
  body: CardsUpdateControlsRequestBody;
};

/**
 * Controls updated
 */
export type CardsUpdateControlsResponse = {
  success?: boolean | undefined;
};

/** @internal */
export type CardsUpdateControlsRequestBody$Outbound = {
  mcc_locks?: string | undefined;
  daily_limit?: number | undefined;
  max_transaction?: number | undefined;
};

/** @internal */
export const CardsUpdateControlsRequestBody$outboundSchema: z.ZodMiniType<
  CardsUpdateControlsRequestBody$Outbound,
  CardsUpdateControlsRequestBody
> = z.pipe(
  z.object({
    mccLocks: z.optional(z.string()),
    dailyLimit: z.optional(z.number()),
    maxTransaction: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      mccLocks: "mcc_locks",
      dailyLimit: "daily_limit",
      maxTransaction: "max_transaction",
    });
  }),
);

export function cardsUpdateControlsRequestBodyToJSON(
  cardsUpdateControlsRequestBody: CardsUpdateControlsRequestBody,
): string {
  return JSON.stringify(
    CardsUpdateControlsRequestBody$outboundSchema.parse(
      cardsUpdateControlsRequestBody,
    ),
  );
}

/** @internal */
export type CardsUpdateControlsRequest$Outbound = {
  id: string;
  body: CardsUpdateControlsRequestBody$Outbound;
};

/** @internal */
export const CardsUpdateControlsRequest$outboundSchema: z.ZodMiniType<
  CardsUpdateControlsRequest$Outbound,
  CardsUpdateControlsRequest
> = z.object({
  id: z.string(),
  body: z.lazy(() => CardsUpdateControlsRequestBody$outboundSchema),
});

export function cardsUpdateControlsRequestToJSON(
  cardsUpdateControlsRequest: CardsUpdateControlsRequest,
): string {
  return JSON.stringify(
    CardsUpdateControlsRequest$outboundSchema.parse(cardsUpdateControlsRequest),
  );
}

/** @internal */
export const CardsUpdateControlsResponse$inboundSchema: z.ZodMiniType<
  CardsUpdateControlsResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function cardsUpdateControlsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsUpdateControlsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsUpdateControlsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsUpdateControlsResponse' from JSON`,
  );
}
