/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CardsListTransactionsRequest = {
  id: string;
};

/**
 * Transactions list
 */
export type CardsListTransactionsResponse = {
  transactions?: Array<components.Transaction> | undefined;
};

/** @internal */
export type CardsListTransactionsRequest$Outbound = {
  id: string;
};

/** @internal */
export const CardsListTransactionsRequest$outboundSchema: z.ZodMiniType<
  CardsListTransactionsRequest$Outbound,
  CardsListTransactionsRequest
> = z.object({
  id: z.string(),
});

export function cardsListTransactionsRequestToJSON(
  cardsListTransactionsRequest: CardsListTransactionsRequest,
): string {
  return JSON.stringify(
    CardsListTransactionsRequest$outboundSchema.parse(
      cardsListTransactionsRequest,
    ),
  );
}

/** @internal */
export const CardsListTransactionsResponse$inboundSchema: z.ZodMiniType<
  CardsListTransactionsResponse,
  unknown
> = z.object({
  transactions: types.optional(z.array(components.Transaction$inboundSchema)),
});

export function cardsListTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsListTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsListTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsListTransactionsResponse' from JSON`,
  );
}
