/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CardsBulkCreateLimitAmount = number | string;

export type Card = {
  purpose: string;
  limitAmount: number | string;
};

export type CardsBulkCreateRequestBody = {
  cards: Array<Card>;
  network?: string | undefined;
  asset?: string | undefined;
};

export type CardsBulkCreateRequest = {
  /**
   * Unique key to prevent duplicate bulk operations
   */
  idempotencyKey?: string | undefined;
  body: CardsBulkCreateRequestBody;
};

export type TotalAllocated = number | string;

/**
 * Cards created
 */
export type CardsBulkCreateResponse = {
  success?: boolean | undefined;
  cards?: Array<components.Card> | undefined;
  totalAllocated?: number | string | undefined;
};

/** @internal */
export type CardsBulkCreateLimitAmount$Outbound = number | string;

/** @internal */
export const CardsBulkCreateLimitAmount$outboundSchema: z.ZodMiniType<
  CardsBulkCreateLimitAmount$Outbound,
  CardsBulkCreateLimitAmount
> = smartUnion([z.number(), z.string()]);

export function cardsBulkCreateLimitAmountToJSON(
  cardsBulkCreateLimitAmount: CardsBulkCreateLimitAmount,
): string {
  return JSON.stringify(
    CardsBulkCreateLimitAmount$outboundSchema.parse(cardsBulkCreateLimitAmount),
  );
}

/** @internal */
export type Card$Outbound = {
  purpose: string;
  limit_amount: number | string;
};

/** @internal */
export const Card$outboundSchema: z.ZodMiniType<Card$Outbound, Card> = z.pipe(
  z.object({
    purpose: z.string(),
    limitAmount: smartUnion([z.number(), z.string()]),
  }),
  z.transform((v) => {
    return remap$(v, {
      limitAmount: "limit_amount",
    });
  }),
);

export function cardToJSON(card: Card): string {
  return JSON.stringify(Card$outboundSchema.parse(card));
}

/** @internal */
export type CardsBulkCreateRequestBody$Outbound = {
  cards: Array<Card$Outbound>;
  network: string;
  asset: string;
};

/** @internal */
export const CardsBulkCreateRequestBody$outboundSchema: z.ZodMiniType<
  CardsBulkCreateRequestBody$Outbound,
  CardsBulkCreateRequestBody
> = z.object({
  cards: z.array(z.lazy(() => Card$outboundSchema)),
  network: z._default(z.string(), "eip155:8453"),
  asset: z._default(z.string(), "USDC"),
});

export function cardsBulkCreateRequestBodyToJSON(
  cardsBulkCreateRequestBody: CardsBulkCreateRequestBody,
): string {
  return JSON.stringify(
    CardsBulkCreateRequestBody$outboundSchema.parse(cardsBulkCreateRequestBody),
  );
}

/** @internal */
export type CardsBulkCreateRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: CardsBulkCreateRequestBody$Outbound;
};

/** @internal */
export const CardsBulkCreateRequest$outboundSchema: z.ZodMiniType<
  CardsBulkCreateRequest$Outbound,
  CardsBulkCreateRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: z.lazy(() => CardsBulkCreateRequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function cardsBulkCreateRequestToJSON(
  cardsBulkCreateRequest: CardsBulkCreateRequest,
): string {
  return JSON.stringify(
    CardsBulkCreateRequest$outboundSchema.parse(cardsBulkCreateRequest),
  );
}

/** @internal */
export const TotalAllocated$inboundSchema: z.ZodMiniType<
  TotalAllocated,
  unknown
> = smartUnion([types.number(), types.string()]);

export function totalAllocatedFromJSON(
  jsonString: string,
): SafeParseResult<TotalAllocated, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TotalAllocated$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TotalAllocated' from JSON`,
  );
}

/** @internal */
export const CardsBulkCreateResponse$inboundSchema: z.ZodMiniType<
  CardsBulkCreateResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    cards: types.optional(z.array(components.Card$inboundSchema)),
    total_allocated: types.optional(
      smartUnion([types.number(), types.string()]),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_allocated": "totalAllocated",
    });
  }),
);

export function cardsBulkCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsBulkCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsBulkCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsBulkCreateResponse' from JSON`,
  );
}
