/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Cards list
 */
export type CardsListResponse = {
  cards?: Array<components.Card> | undefined;
};

/** @internal */
export const CardsListResponse$inboundSchema: z.ZodMiniType<
  CardsListResponse,
  unknown
> = z.object({
  cards: types.optional(z.array(components.Card$inboundSchema)),
});

export function cardsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<CardsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardsListResponse' from JSON`,
  );
}
