/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FundingGetWalletBalanceRequest = {
  network: string;
  asset: string;
  /**
   * Wallet address (defaults to authenticated wallet)
   */
  address?: string | undefined;
};

/**
 * On-chain balance
 */
export type FundingGetWalletBalanceResponse = {
  network?: string | undefined;
  asset?: string | undefined;
  address?: string | undefined;
  /**
   * Token balance in human units (e.g., 42.50 USDC)
   */
  balance?: number | undefined;
};

/** @internal */
export type FundingGetWalletBalanceRequest$Outbound = {
  network: string;
  asset: string;
  address?: string | undefined;
};

/** @internal */
export const FundingGetWalletBalanceRequest$outboundSchema: z.ZodMiniType<
  FundingGetWalletBalanceRequest$Outbound,
  FundingGetWalletBalanceRequest
> = z.object({
  network: z.string(),
  asset: z.string(),
  address: z.optional(z.string()),
});

export function fundingGetWalletBalanceRequestToJSON(
  fundingGetWalletBalanceRequest: FundingGetWalletBalanceRequest,
): string {
  return JSON.stringify(
    FundingGetWalletBalanceRequest$outboundSchema.parse(
      fundingGetWalletBalanceRequest,
    ),
  );
}

/** @internal */
export const FundingGetWalletBalanceResponse$inboundSchema: z.ZodMiniType<
  FundingGetWalletBalanceResponse,
  unknown
> = z.object({
  network: types.optional(types.string()),
  asset: types.optional(types.string()),
  address: types.optional(types.string()),
  balance: types.optional(types.number()),
});

export function fundingGetWalletBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<FundingGetWalletBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FundingGetWalletBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FundingGetWalletBalanceResponse' from JSON`,
  );
}
