/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Balance data
 */
export type FundingGetBalanceResponse = {
  balances?: Array<components.Balance> | undefined;
};

/** @internal */
export const FundingGetBalanceResponse$inboundSchema: z.ZodMiniType<
  FundingGetBalanceResponse,
  unknown
> = z.object({
  balances: types.optional(z.array(components.Balance$inboundSchema)),
});

export function fundingGetBalanceResponseFromJSON(
  jsonString: string,
): SafeParseResult<FundingGetBalanceResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FundingGetBalanceResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FundingGetBalanceResponse' from JSON`,
  );
}
