/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Registry = {
  symbol?: string | undefined;
  type?: string | undefined;
  decimals?: number | undefined;
  contract?: string | undefined;
};

/**
 * Token registry
 */
export type FundingListTokensResponse = {
  /**
   * Map of CAIP-2 network IDs to supported tokens
   */
  registry?: { [k: string]: Array<Registry> } | undefined;
};

/** @internal */
export const Registry$inboundSchema: z.ZodMiniType<Registry, unknown> = z
  .object({
    symbol: types.optional(types.string()),
    type: types.optional(types.string()),
    decimals: types.optional(types.number()),
    contract: types.optional(types.string()),
  });

export function registryFromJSON(
  jsonString: string,
): SafeParseResult<Registry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Registry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Registry' from JSON`,
  );
}

/** @internal */
export const FundingListTokensResponse$inboundSchema: z.ZodMiniType<
  FundingListTokensResponse,
  unknown
> = z.object({
  registry: types.optional(
    z.record(z.string(), z.array(z.lazy(() => Registry$inboundSchema))),
  ),
});

export function fundingListTokensResponseFromJSON(
  jsonString: string,
): SafeParseResult<FundingListTokensResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FundingListTokensResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FundingListTokensResponse' from JSON`,
  );
}
