/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type FundingVerifyRequest = {
  /**
   * On-chain transaction hash to verify
   */
  txHash: string;
  network?: string | undefined;
  asset?: string | undefined;
};

export const FundingVerifyStatus = {
  Confirmed: "confirmed",
  Pending: "pending",
} as const;
export type FundingVerifyStatus = OpenEnum<typeof FundingVerifyStatus>;

/**
 * Amount credited from this transaction
 */
export type Funded = number | string;

/**
 * Funding verified or pending
 */
export type FundingVerifyResponse = {
  success?: boolean | undefined;
  status?: FundingVerifyStatus | undefined;
  /**
   * Amount credited from this transaction
   */
  funded?: number | string | undefined;
  balance?: components.Balance | undefined;
};

/** @internal */
export type FundingVerifyRequest$Outbound = {
  tx_hash: string;
  network: string;
  asset: string;
};

/** @internal */
export const FundingVerifyRequest$outboundSchema: z.ZodMiniType<
  FundingVerifyRequest$Outbound,
  FundingVerifyRequest
> = z.pipe(
  z.object({
    txHash: z.string(),
    network: z._default(z.string(), "eip155:8453"),
    asset: z._default(z.string(), "USDC"),
  }),
  z.transform((v) => {
    return remap$(v, {
      txHash: "tx_hash",
    });
  }),
);

export function fundingVerifyRequestToJSON(
  fundingVerifyRequest: FundingVerifyRequest,
): string {
  return JSON.stringify(
    FundingVerifyRequest$outboundSchema.parse(fundingVerifyRequest),
  );
}

/** @internal */
export const FundingVerifyStatus$inboundSchema: z.ZodMiniType<
  FundingVerifyStatus,
  unknown
> = openEnums.inboundSchema(FundingVerifyStatus);

/** @internal */
export const Funded$inboundSchema: z.ZodMiniType<Funded, unknown> = smartUnion([
  types.number(),
  types.string(),
]);

export function fundedFromJSON(
  jsonString: string,
): SafeParseResult<Funded, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Funded$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Funded' from JSON`,
  );
}

/** @internal */
export const FundingVerifyResponse$inboundSchema: z.ZodMiniType<
  FundingVerifyResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
  status: types.optional(FundingVerifyStatus$inboundSchema),
  funded: types.optional(smartUnion([types.number(), types.string()])),
  balance: types.optional(components.Balance$inboundSchema),
});

export function fundingVerifyResponseFromJSON(
  jsonString: string,
): SafeParseResult<FundingVerifyResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FundingVerifyResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FundingVerifyResponse' from JSON`,
  );
}
