/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Key generated
 */
export type KeysCreateResponse = {
  apiKey?: string | undefined;
};

/** @internal */
export const KeysCreateResponse$inboundSchema: z.ZodMiniType<
  KeysCreateResponse,
  unknown
> = z.pipe(
  z.object({
    api_key: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_key": "apiKey",
    });
  }),
);

export function keysCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<KeysCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeysCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeysCreateResponse' from JSON`,
  );
}
