/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type KeysRevokeRequest = {
  hash: string;
};

/**
 * Key revoked
 */
export type KeysRevokeResponse = {
  success?: boolean | undefined;
};

/** @internal */
export type KeysRevokeRequest$Outbound = {
  hash: string;
};

/** @internal */
export const KeysRevokeRequest$outboundSchema: z.ZodMiniType<
  KeysRevokeRequest$Outbound,
  KeysRevokeRequest
> = z.object({
  hash: z.string(),
});

export function keysRevokeRequestToJSON(
  keysRevokeRequest: KeysRevokeRequest,
): string {
  return JSON.stringify(
    KeysRevokeRequest$outboundSchema.parse(keysRevokeRequest),
  );
}

/** @internal */
export const KeysRevokeResponse$inboundSchema: z.ZodMiniType<
  KeysRevokeResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function keysRevokeResponseFromJSON(
  jsonString: string,
): SafeParseResult<KeysRevokeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeysRevokeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeysRevokeResponse' from JSON`,
  );
}
