/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Key valid
 */
export type KeysValidateResponse = {
  valid?: boolean | undefined;
  walletAddress?: string | undefined;
  authenticatedAt?: Date | undefined;
};

/** @internal */
export const KeysValidateResponse$inboundSchema: z.ZodMiniType<
  KeysValidateResponse,
  unknown
> = z.pipe(
  z.object({
    valid: types.optional(types.boolean()),
    wallet_address: types.optional(types.string()),
    authenticated_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "wallet_address": "walletAddress",
      "authenticated_at": "authenticatedAt",
    });
  }),
);

export function keysValidateResponseFromJSON(
  jsonString: string,
): SafeParseResult<KeysValidateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeysValidateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeysValidateResponse' from JSON`,
  );
}
