/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Keys list
 */
export type KeysListResponse = {
  keys?: Array<components.ApiKey> | undefined;
};

/** @internal */
export const KeysListResponse$inboundSchema: z.ZodMiniType<
  KeysListResponse,
  unknown
> = z.object({
  keys: types.optional(z.array(components.ApiKey$inboundSchema)),
});

export function keysListResponseFromJSON(
  jsonString: string,
): SafeParseResult<KeysListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => KeysListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'KeysListResponse' from JSON`,
  );
}
