/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppStreamsTickRequest = {
  streamId: string;
  cardId: string;
  cardToken: string;
};

export type MppStreamsTickTotalTicked = number | string;

export type Remaining = number | string;

/**
 * Tick processed
 */
export type MppStreamsTickResponse = {
  totalTicked?: number | string | undefined;
  remaining?: number | string | undefined;
};

/** @internal */
export type MppStreamsTickRequest$Outbound = {
  stream_id: string;
  card_id: string;
  card_token: string;
};

/** @internal */
export const MppStreamsTickRequest$outboundSchema: z.ZodMiniType<
  MppStreamsTickRequest$Outbound,
  MppStreamsTickRequest
> = z.pipe(
  z.object({
    streamId: z.string(),
    cardId: z.string(),
    cardToken: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      streamId: "stream_id",
      cardId: "card_id",
      cardToken: "card_token",
    });
  }),
);

export function mppStreamsTickRequestToJSON(
  mppStreamsTickRequest: MppStreamsTickRequest,
): string {
  return JSON.stringify(
    MppStreamsTickRequest$outboundSchema.parse(mppStreamsTickRequest),
  );
}

/** @internal */
export const MppStreamsTickTotalTicked$inboundSchema: z.ZodMiniType<
  MppStreamsTickTotalTicked,
  unknown
> = smartUnion([types.number(), types.string()]);

export function mppStreamsTickTotalTickedFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsTickTotalTicked, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsTickTotalTicked$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsTickTotalTicked' from JSON`,
  );
}

/** @internal */
export const Remaining$inboundSchema: z.ZodMiniType<Remaining, unknown> =
  smartUnion([types.number(), types.string()]);

export function remainingFromJSON(
  jsonString: string,
): SafeParseResult<Remaining, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Remaining$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Remaining' from JSON`,
  );
}

/** @internal */
export const MppStreamsTickResponse$inboundSchema: z.ZodMiniType<
  MppStreamsTickResponse,
  unknown
> = z.pipe(
  z.object({
    total_ticked: types.optional(smartUnion([types.number(), types.string()])),
    remaining: types.optional(smartUnion([types.number(), types.string()])),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_ticked": "totalTicked",
    });
  }),
);

export function mppStreamsTickResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsTickResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsTickResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsTickResponse' from JSON`,
  );
}
