/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppStreamsCloseRequest = {
  streamId: string;
};

export type FinalAmount = number | string;

/**
 * Stream closed
 */
export type MppStreamsCloseResponse = {
  finalAmount?: number | string | undefined;
  status?: string | undefined;
};

/** @internal */
export type MppStreamsCloseRequest$Outbound = {
  stream_id: string;
};

/** @internal */
export const MppStreamsCloseRequest$outboundSchema: z.ZodMiniType<
  MppStreamsCloseRequest$Outbound,
  MppStreamsCloseRequest
> = z.pipe(
  z.object({
    streamId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      streamId: "stream_id",
    });
  }),
);

export function mppStreamsCloseRequestToJSON(
  mppStreamsCloseRequest: MppStreamsCloseRequest,
): string {
  return JSON.stringify(
    MppStreamsCloseRequest$outboundSchema.parse(mppStreamsCloseRequest),
  );
}

/** @internal */
export const FinalAmount$inboundSchema: z.ZodMiniType<FinalAmount, unknown> =
  smartUnion([types.number(), types.string()]);

export function finalAmountFromJSON(
  jsonString: string,
): SafeParseResult<FinalAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FinalAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FinalAmount' from JSON`,
  );
}

/** @internal */
export const MppStreamsCloseResponse$inboundSchema: z.ZodMiniType<
  MppStreamsCloseResponse,
  unknown
> = z.pipe(
  z.object({
    final_amount: types.optional(smartUnion([types.number(), types.string()])),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "final_amount": "finalAmount",
    });
  }),
);

export function mppStreamsCloseResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsCloseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsCloseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsCloseResponse' from JSON`,
  );
}
