/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppStreamsGetRequest = {
  id: string;
};

/**
 * Stream details
 */
export type MppStreamsGetResponse = {
  id?: string | undefined;
  cardId?: string | undefined;
  budget?: number | undefined;
  tickAmount?: number | undefined;
  totalTicked?: number | undefined;
  status?: string | undefined;
};

/** @internal */
export type MppStreamsGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const MppStreamsGetRequest$outboundSchema: z.ZodMiniType<
  MppStreamsGetRequest$Outbound,
  MppStreamsGetRequest
> = z.object({
  id: z.string(),
});

export function mppStreamsGetRequestToJSON(
  mppStreamsGetRequest: MppStreamsGetRequest,
): string {
  return JSON.stringify(
    MppStreamsGetRequest$outboundSchema.parse(mppStreamsGetRequest),
  );
}

/** @internal */
export const MppStreamsGetResponse$inboundSchema: z.ZodMiniType<
  MppStreamsGetResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    card_id: types.optional(types.string()),
    budget: types.optional(types.number()),
    tick_amount: types.optional(types.number()),
    total_ticked: types.optional(types.number()),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
      "tick_amount": "tickAmount",
      "total_ticked": "totalTicked",
    });
  }),
);

export function mppStreamsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsGetResponse' from JSON`,
  );
}
