/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppStreamsOpenRequest = {
  cardId: string;
  cardToken: string;
  /**
   * Total budget for the stream in USDC
   */
  budget: number;
  /**
   * Amount per tick
   */
  tickAmount: number;
  receiverCardId?: string | undefined;
};

/**
 * Stream opened
 */
export type MppStreamsOpenResponse = {
  id?: string | undefined;
  cardId?: string | undefined;
  budget?: number | undefined;
  tickAmount?: number | undefined;
  totalTicked?: number | undefined;
  status?: string | undefined;
  receiverCardId?: string | undefined;
};

/** @internal */
export type MppStreamsOpenRequest$Outbound = {
  card_id: string;
  card_token: string;
  budget: number;
  tick_amount: number;
  receiver_card_id?: string | undefined;
};

/** @internal */
export const MppStreamsOpenRequest$outboundSchema: z.ZodMiniType<
  MppStreamsOpenRequest$Outbound,
  MppStreamsOpenRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    budget: z.number(),
    tickAmount: z.number(),
    receiverCardId: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
      tickAmount: "tick_amount",
      receiverCardId: "receiver_card_id",
    });
  }),
);

export function mppStreamsOpenRequestToJSON(
  mppStreamsOpenRequest: MppStreamsOpenRequest,
): string {
  return JSON.stringify(
    MppStreamsOpenRequest$outboundSchema.parse(mppStreamsOpenRequest),
  );
}

/** @internal */
export const MppStreamsOpenResponse$inboundSchema: z.ZodMiniType<
  MppStreamsOpenResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    card_id: types.optional(types.string()),
    budget: types.optional(types.number()),
    tick_amount: types.optional(types.number()),
    total_ticked: types.optional(types.number()),
    status: types.optional(types.string()),
    receiver_card_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
      "tick_amount": "tickAmount",
      "total_ticked": "totalTicked",
      "receiver_card_id": "receiverCardId",
    });
  }),
);

export function mppStreamsOpenResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsOpenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsOpenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsOpenResponse' from JSON`,
  );
}
