/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppPayRequest = {
  cardId: string;
  cardToken: string;
  amount: number;
  merchant?: string | undefined;
  merchantAddress?: string | undefined;
  network?: string | undefined;
};

/**
 * Payment authorized
 */
export type MppPayResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
};

/** @internal */
export type MppPayRequest$Outbound = {
  card_id: string;
  card_token: string;
  amount: number;
  merchant?: string | undefined;
  merchant_address?: string | undefined;
  network: string;
};

/** @internal */
export const MppPayRequest$outboundSchema: z.ZodMiniType<
  MppPayRequest$Outbound,
  MppPayRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    amount: z.number(),
    merchant: z.optional(z.string()),
    merchantAddress: z.optional(z.string()),
    network: z._default(z.string(), "eip155:8453"),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
      merchantAddress: "merchant_address",
    });
  }),
);

export function mppPayRequestToJSON(mppPayRequest: MppPayRequest): string {
  return JSON.stringify(MppPayRequest$outboundSchema.parse(mppPayRequest));
}

/** @internal */
export const MppPayResponse$inboundSchema: z.ZodMiniType<
  MppPayResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
    });
  }),
);

export function mppPayResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppPayResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppPayResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppPayResponse' from JSON`,
  );
}
