/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PaymentData = {};

export type MppReceiveRequest = {
  paymentData?: PaymentData | undefined;
};

/**
 * Payment verified
 */
export type MppReceiveResponse = {
  verified?: boolean | undefined;
};

/** @internal */
export type PaymentData$Outbound = {};

/** @internal */
export const PaymentData$outboundSchema: z.ZodMiniType<
  PaymentData$Outbound,
  PaymentData
> = z.object({});

export function paymentDataToJSON(paymentData: PaymentData): string {
  return JSON.stringify(PaymentData$outboundSchema.parse(paymentData));
}

/** @internal */
export type MppReceiveRequest$Outbound = {
  payment_data?: PaymentData$Outbound | undefined;
};

/** @internal */
export const MppReceiveRequest$outboundSchema: z.ZodMiniType<
  MppReceiveRequest$Outbound,
  MppReceiveRequest
> = z.pipe(
  z.object({
    paymentData: z.optional(z.lazy(() => PaymentData$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentData: "payment_data",
    });
  }),
);

export function mppReceiveRequestToJSON(
  mppReceiveRequest: MppReceiveRequest,
): string {
  return JSON.stringify(
    MppReceiveRequest$outboundSchema.parse(mppReceiveRequest),
  );
}

/** @internal */
export const MppReceiveResponse$inboundSchema: z.ZodMiniType<
  MppReceiveResponse,
  unknown
> = z.object({
  verified: types.optional(types.boolean()),
});

export function mppReceiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppReceiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppReceiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppReceiveResponse' from JSON`,
  );
}
