/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppStreamsGetRequest = {
  id: string;
};

export type MppStreamsGetBudget = number | string;

export type MppStreamsGetTickAmount = number | string;

export type MppStreamsGetTotalTicked = number | string;

/**
 * Stream details
 */
export type MppStreamsGetResponse = {
  id?: string | undefined;
  cardId?: string | undefined;
  budget?: number | string | undefined;
  tickAmount?: number | string | undefined;
  totalTicked?: number | string | undefined;
  status?: string | undefined;
};

/** @internal */
export type MppStreamsGetRequest$Outbound = {
  id: string;
};

/** @internal */
export const MppStreamsGetRequest$outboundSchema: z.ZodMiniType<
  MppStreamsGetRequest$Outbound,
  MppStreamsGetRequest
> = z.object({
  id: z.string(),
});

export function mppStreamsGetRequestToJSON(
  mppStreamsGetRequest: MppStreamsGetRequest,
): string {
  return JSON.stringify(
    MppStreamsGetRequest$outboundSchema.parse(mppStreamsGetRequest),
  );
}

/** @internal */
export const MppStreamsGetBudget$inboundSchema: z.ZodMiniType<
  MppStreamsGetBudget,
  unknown
> = smartUnion([types.number(), types.string()]);

export function mppStreamsGetBudgetFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsGetBudget, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsGetBudget$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsGetBudget' from JSON`,
  );
}

/** @internal */
export const MppStreamsGetTickAmount$inboundSchema: z.ZodMiniType<
  MppStreamsGetTickAmount,
  unknown
> = smartUnion([types.number(), types.string()]);

export function mppStreamsGetTickAmountFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsGetTickAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsGetTickAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsGetTickAmount' from JSON`,
  );
}

/** @internal */
export const MppStreamsGetTotalTicked$inboundSchema: z.ZodMiniType<
  MppStreamsGetTotalTicked,
  unknown
> = smartUnion([types.number(), types.string()]);

export function mppStreamsGetTotalTickedFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsGetTotalTicked, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsGetTotalTicked$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsGetTotalTicked' from JSON`,
  );
}

/** @internal */
export const MppStreamsGetResponse$inboundSchema: z.ZodMiniType<
  MppStreamsGetResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    card_id: types.optional(types.string()),
    budget: types.optional(smartUnion([types.number(), types.string()])),
    tick_amount: types.optional(smartUnion([types.number(), types.string()])),
    total_ticked: types.optional(smartUnion([types.number(), types.string()])),
    status: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_id": "cardId",
      "tick_amount": "tickAmount",
      "total_ticked": "totalTicked",
    });
  }),
);

export function mppStreamsGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppStreamsGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppStreamsGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppStreamsGetResponse' from JSON`,
  );
}
