/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppCreateSessionRequest = {
  cardId: string;
  cardToken: string;
  merchant: string;
};

/**
 * Session created
 */
export type MppCreateSessionResponse = {
  sessionId?: string | undefined;
};

/** @internal */
export type MppCreateSessionRequest$Outbound = {
  card_id: string;
  card_token: string;
  merchant: string;
};

/** @internal */
export const MppCreateSessionRequest$outboundSchema: z.ZodMiniType<
  MppCreateSessionRequest$Outbound,
  MppCreateSessionRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    merchant: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
    });
  }),
);

export function mppCreateSessionRequestToJSON(
  mppCreateSessionRequest: MppCreateSessionRequest,
): string {
  return JSON.stringify(
    MppCreateSessionRequest$outboundSchema.parse(mppCreateSessionRequest),
  );
}

/** @internal */
export const MppCreateSessionResponse$inboundSchema: z.ZodMiniType<
  MppCreateSessionResponse,
  unknown
> = z.pipe(
  z.object({
    session_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "session_id": "sessionId",
    });
  }),
);

export function mppCreateSessionResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppCreateSessionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppCreateSessionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppCreateSessionResponse' from JSON`,
  );
}
