/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type MppDiscoverRequest = {
  url: string;
};

export type Capabilities = {};

/**
 * Discovery result
 */
export type MppDiscoverResponse = {
  supportsMpp?: boolean | undefined;
  capabilities?: Capabilities | undefined;
};

/** @internal */
export type MppDiscoverRequest$Outbound = {
  url: string;
};

/** @internal */
export const MppDiscoverRequest$outboundSchema: z.ZodMiniType<
  MppDiscoverRequest$Outbound,
  MppDiscoverRequest
> = z.object({
  url: z.string(),
});

export function mppDiscoverRequestToJSON(
  mppDiscoverRequest: MppDiscoverRequest,
): string {
  return JSON.stringify(
    MppDiscoverRequest$outboundSchema.parse(mppDiscoverRequest),
  );
}

/** @internal */
export const Capabilities$inboundSchema: z.ZodMiniType<Capabilities, unknown> =
  z.object({});

export function capabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<Capabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Capabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Capabilities' from JSON`,
  );
}

/** @internal */
export const MppDiscoverResponse$inboundSchema: z.ZodMiniType<
  MppDiscoverResponse,
  unknown
> = z.pipe(
  z.object({
    supports_mpp: types.optional(types.boolean()),
    capabilities: types.optional(z.lazy(() => Capabilities$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "supports_mpp": "supportsMpp",
    });
  }),
);

export function mppDiscoverResponseFromJSON(
  jsonString: string,
): SafeParseResult<MppDiscoverResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MppDiscoverResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MppDiscoverResponse' from JSON`,
  );
}
