/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PayLinksGetStatusRequest = {
  code: string;
};

/**
 * Status
 */
export type PayLinksGetStatusResponse = {
  status?: string | undefined;
  confirmedAt?: Date | null | undefined;
};

/** @internal */
export type PayLinksGetStatusRequest$Outbound = {
  code: string;
};

/** @internal */
export const PayLinksGetStatusRequest$outboundSchema: z.ZodMiniType<
  PayLinksGetStatusRequest$Outbound,
  PayLinksGetStatusRequest
> = z.object({
  code: z.string(),
});

export function payLinksGetStatusRequestToJSON(
  payLinksGetStatusRequest: PayLinksGetStatusRequest,
): string {
  return JSON.stringify(
    PayLinksGetStatusRequest$outboundSchema.parse(payLinksGetStatusRequest),
  );
}

/** @internal */
export const PayLinksGetStatusResponse$inboundSchema: z.ZodMiniType<
  PayLinksGetStatusResponse,
  unknown
> = z.pipe(
  z.object({
    status: types.optional(types.string()),
    confirmed_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "confirmed_at": "confirmedAt",
    });
  }),
);

export function payLinksGetStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksGetStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksGetStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksGetStatusResponse' from JSON`,
  );
}
