/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PayLinksCancelRequest = {
  code: string;
};

/**
 * Cancelled
 */
export type PayLinksCancelResponse = {
  success?: boolean | undefined;
};

/** @internal */
export type PayLinksCancelRequest$Outbound = {
  code: string;
};

/** @internal */
export const PayLinksCancelRequest$outboundSchema: z.ZodMiniType<
  PayLinksCancelRequest$Outbound,
  PayLinksCancelRequest
> = z.object({
  code: z.string(),
});

export function payLinksCancelRequestToJSON(
  payLinksCancelRequest: PayLinksCancelRequest,
): string {
  return JSON.stringify(
    PayLinksCancelRequest$outboundSchema.parse(payLinksCancelRequest),
  );
}

/** @internal */
export const PayLinksCancelResponse$inboundSchema: z.ZodMiniType<
  PayLinksCancelResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function payLinksCancelResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksCancelResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksCancelResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksCancelResponse' from JSON`,
  );
}
