/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PayLinksPrepareRequest = {
  code: string;
};

/**
 * Payment intent
 */
export type PayLinksPrepareResponse = {
  intent?: string | undefined;
  acceptedProtocols?: Array<string> | undefined;
  treasuryAddress?: string | undefined;
  tokenContract?: string | undefined;
};

/** @internal */
export type PayLinksPrepareRequest$Outbound = {
  code: string;
};

/** @internal */
export const PayLinksPrepareRequest$outboundSchema: z.ZodMiniType<
  PayLinksPrepareRequest$Outbound,
  PayLinksPrepareRequest
> = z.object({
  code: z.string(),
});

export function payLinksPrepareRequestToJSON(
  payLinksPrepareRequest: PayLinksPrepareRequest,
): string {
  return JSON.stringify(
    PayLinksPrepareRequest$outboundSchema.parse(payLinksPrepareRequest),
  );
}

/** @internal */
export const PayLinksPrepareResponse$inboundSchema: z.ZodMiniType<
  PayLinksPrepareResponse,
  unknown
> = z.pipe(
  z.object({
    intent: types.optional(types.string()),
    accepted_protocols: types.optional(z.array(types.string())),
    treasury_address: types.optional(types.string()),
    token_contract: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "accepted_protocols": "acceptedProtocols",
      "treasury_address": "treasuryAddress",
      "token_contract": "tokenContract",
    });
  }),
);

export function payLinksPrepareResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksPrepareResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksPrepareResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksPrepareResponse' from JSON`,
  );
}
