/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RequestBody2 = {
  txHash?: string | undefined;
  fromAddress?: string | undefined;
  amount?: number | undefined;
};

export type RequestBody1 = {
  protocol?: string | undefined;
  payerCardId?: string | undefined;
  payerCardToken?: string | undefined;
};

export type PayLinksSettleRequestBody = RequestBody1 | RequestBody2;

export type PayLinksSettleRequest = {
  code: string;
  body: RequestBody1 | RequestBody2;
};

/**
 * Settlement processed
 */
export type PayLinksSettleResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
};

/** @internal */
export type RequestBody2$Outbound = {
  tx_hash?: string | undefined;
  from_address?: string | undefined;
  amount?: number | undefined;
};

/** @internal */
export const RequestBody2$outboundSchema: z.ZodMiniType<
  RequestBody2$Outbound,
  RequestBody2
> = z.pipe(
  z.object({
    txHash: z.optional(z.string()),
    fromAddress: z.optional(z.string()),
    amount: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      txHash: "tx_hash",
      fromAddress: "from_address",
    });
  }),
);

export function requestBody2ToJSON(requestBody2: RequestBody2): string {
  return JSON.stringify(RequestBody2$outboundSchema.parse(requestBody2));
}

/** @internal */
export type RequestBody1$Outbound = {
  protocol?: string | undefined;
  payer_card_id?: string | undefined;
  payer_card_token?: string | undefined;
};

/** @internal */
export const RequestBody1$outboundSchema: z.ZodMiniType<
  RequestBody1$Outbound,
  RequestBody1
> = z.pipe(
  z.object({
    protocol: z.optional(z.string()),
    payerCardId: z.optional(z.string()),
    payerCardToken: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      payerCardId: "payer_card_id",
      payerCardToken: "payer_card_token",
    });
  }),
);

export function requestBody1ToJSON(requestBody1: RequestBody1): string {
  return JSON.stringify(RequestBody1$outboundSchema.parse(requestBody1));
}

/** @internal */
export type PayLinksSettleRequestBody$Outbound =
  | RequestBody1$Outbound
  | RequestBody2$Outbound;

/** @internal */
export const PayLinksSettleRequestBody$outboundSchema: z.ZodMiniType<
  PayLinksSettleRequestBody$Outbound,
  PayLinksSettleRequestBody
> = smartUnion([
  z.lazy(() => RequestBody1$outboundSchema),
  z.lazy(() => RequestBody2$outboundSchema),
]);

export function payLinksSettleRequestBodyToJSON(
  payLinksSettleRequestBody: PayLinksSettleRequestBody,
): string {
  return JSON.stringify(
    PayLinksSettleRequestBody$outboundSchema.parse(payLinksSettleRequestBody),
  );
}

/** @internal */
export type PayLinksSettleRequest$Outbound = {
  code: string;
  body: RequestBody1$Outbound | RequestBody2$Outbound;
};

/** @internal */
export const PayLinksSettleRequest$outboundSchema: z.ZodMiniType<
  PayLinksSettleRequest$Outbound,
  PayLinksSettleRequest
> = z.object({
  code: z.string(),
  body: smartUnion([
    z.lazy(() => RequestBody1$outboundSchema),
    z.lazy(() => RequestBody2$outboundSchema),
  ]),
});

export function payLinksSettleRequestToJSON(
  payLinksSettleRequest: PayLinksSettleRequest,
): string {
  return JSON.stringify(
    PayLinksSettleRequest$outboundSchema.parse(payLinksSettleRequest),
  );
}

/** @internal */
export const PayLinksSettleResponse$inboundSchema: z.ZodMiniType<
  PayLinksSettleResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
    });
  }),
);

export function payLinksSettleResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksSettleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksSettleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksSettleResponse' from JSON`,
  );
}
