/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PayLinksResolveRequest = {
  code: string;
};

export const PayLinksResolveType = {
  Receive: "receive",
  Merchant: "merchant",
} as const;
export type PayLinksResolveType = OpenEnum<typeof PayLinksResolveType>;

/**
 * Resolved data
 */
export type PayLinksResolveResponse = {
  type?: PayLinksResolveType | undefined;
};

/** @internal */
export type PayLinksResolveRequest$Outbound = {
  code: string;
};

/** @internal */
export const PayLinksResolveRequest$outboundSchema: z.ZodMiniType<
  PayLinksResolveRequest$Outbound,
  PayLinksResolveRequest
> = z.object({
  code: z.string(),
});

export function payLinksResolveRequestToJSON(
  payLinksResolveRequest: PayLinksResolveRequest,
): string {
  return JSON.stringify(
    PayLinksResolveRequest$outboundSchema.parse(payLinksResolveRequest),
  );
}

/** @internal */
export const PayLinksResolveType$inboundSchema: z.ZodMiniType<
  PayLinksResolveType,
  unknown
> = openEnums.inboundSchema(PayLinksResolveType);

/** @internal */
export const PayLinksResolveResponse$inboundSchema: z.ZodMiniType<
  PayLinksResolveResponse,
  unknown
> = z.object({
  type: types.optional(PayLinksResolveType$inboundSchema),
});

export function payLinksResolveResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksResolveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksResolveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksResolveResponse' from JSON`,
  );
}
