/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PayLinksGetRequest = {
  code: string;
};

/** @internal */
export type PayLinksGetRequest$Outbound = {
  code: string;
};

/** @internal */
export const PayLinksGetRequest$outboundSchema: z.ZodMiniType<
  PayLinksGetRequest$Outbound,
  PayLinksGetRequest
> = z.object({
  code: z.string(),
});

export function payLinksGetRequestToJSON(
  payLinksGetRequest: PayLinksGetRequest,
): string {
  return JSON.stringify(
    PayLinksGetRequest$outboundSchema.parse(payLinksGetRequest),
  );
}
