/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Pay links list
 */
export type PayLinksListResponse = {
  links?: Array<components.PayLink> | undefined;
};

/** @internal */
export const PayLinksListResponse$inboundSchema: z.ZodMiniType<
  PayLinksListResponse,
  unknown
> = z.object({
  links: types.optional(z.array(components.PayLink$inboundSchema)),
});

export function payLinksListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksListResponse' from JSON`,
  );
}
