/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { smartUnion } from "../../types/smart-union.js";

/**
 * Fixed amount (null for open-amount)
 */
export type PayLinksCreateAmount = string | number;

/**
 * SINGLE for one-time, RECURRING for multi-use
 */
export const PayLinksCreateType = {
  Single: "SINGLE",
  Recurring: "RECURRING",
} as const;
/**
 * SINGLE for one-time, RECURRING for multi-use
 */
export type PayLinksCreateType = ClosedEnum<typeof PayLinksCreateType>;

export type PayLinksCreateRequest = {
  cardId: string;
  /**
   * Fixed amount (null for open-amount)
   */
  amount?: string | number | null | undefined;
  memo?: string | undefined;
  /**
   * SINGLE for one-time, RECURRING for multi-use
   */
  type?: PayLinksCreateType | undefined;
  maxUses?: number | undefined;
  /**
   * Hours until expiry
   */
  expiresIn?: number | undefined;
};

/** @internal */
export type PayLinksCreateAmount$Outbound = string | number;

/** @internal */
export const PayLinksCreateAmount$outboundSchema: z.ZodMiniType<
  PayLinksCreateAmount$Outbound,
  PayLinksCreateAmount
> = smartUnion([z.string(), z.number()]);

export function payLinksCreateAmountToJSON(
  payLinksCreateAmount: PayLinksCreateAmount,
): string {
  return JSON.stringify(
    PayLinksCreateAmount$outboundSchema.parse(payLinksCreateAmount),
  );
}

/** @internal */
export const PayLinksCreateType$outboundSchema: z.ZodMiniEnum<
  typeof PayLinksCreateType
> = z.enum(PayLinksCreateType);

/** @internal */
export type PayLinksCreateRequest$Outbound = {
  card_id: string;
  amount?: string | number | null | undefined;
  memo?: string | undefined;
  type: string;
  max_uses: number;
  expires_in?: number | undefined;
};

/** @internal */
export const PayLinksCreateRequest$outboundSchema: z.ZodMiniType<
  PayLinksCreateRequest$Outbound,
  PayLinksCreateRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    amount: z.optional(z.nullable(smartUnion([z.string(), z.number()]))),
    memo: z.optional(z.string()),
    type: z._default(PayLinksCreateType$outboundSchema, "SINGLE"),
    maxUses: z._default(z.int(), 1),
    expiresIn: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      maxUses: "max_uses",
      expiresIn: "expires_in",
    });
  }),
);

export function payLinksCreateRequestToJSON(
  payLinksCreateRequest: PayLinksCreateRequest,
): string {
  return JSON.stringify(
    PayLinksCreateRequest$outboundSchema.parse(payLinksCreateRequest),
  );
}
