/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * SINGLE for one-time, RECURRING for multi-use
 */
export const PayLinksCreateType = {
  Single: "SINGLE",
  Recurring: "RECURRING",
} as const;
/**
 * SINGLE for one-time, RECURRING for multi-use
 */
export type PayLinksCreateType = ClosedEnum<typeof PayLinksCreateType>;

export type PayLinksCreateRequest = {
  cardId: string;
  /**
   * Fixed amount (null for open-amount)
   */
  amount?: number | null | undefined;
  memo?: string | undefined;
  /**
   * SINGLE for one-time, RECURRING for multi-use
   */
  type?: PayLinksCreateType | undefined;
  maxUses?: number | undefined;
  /**
   * Hours until expiry
   */
  expiresIn?: number | undefined;
};

/**
 * Pay link created
 */
export type PayLinksCreateResponse = {
  success?: boolean | undefined;
  payLink?: components.PayLink | undefined;
};

/** @internal */
export const PayLinksCreateType$outboundSchema: z.ZodMiniEnum<
  typeof PayLinksCreateType
> = z.enum(PayLinksCreateType);

/** @internal */
export type PayLinksCreateRequest$Outbound = {
  card_id: string;
  amount?: number | null | undefined;
  memo?: string | undefined;
  type: string;
  max_uses: number;
  expires_in?: number | undefined;
};

/** @internal */
export const PayLinksCreateRequest$outboundSchema: z.ZodMiniType<
  PayLinksCreateRequest$Outbound,
  PayLinksCreateRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    amount: z.optional(z.nullable(z.number())),
    memo: z.optional(z.string()),
    type: z._default(PayLinksCreateType$outboundSchema, "SINGLE"),
    maxUses: z._default(z.int(), 1),
    expiresIn: z.optional(z.number()),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      maxUses: "max_uses",
      expiresIn: "expires_in",
    });
  }),
);

export function payLinksCreateRequestToJSON(
  payLinksCreateRequest: PayLinksCreateRequest,
): string {
  return JSON.stringify(
    PayLinksCreateRequest$outboundSchema.parse(payLinksCreateRequest),
  );
}

/** @internal */
export const PayLinksCreateResponse$inboundSchema: z.ZodMiniType<
  PayLinksCreateResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    pay_link: types.optional(components.PayLink$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "pay_link": "payLink",
    });
  }),
);

export function payLinksCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<PayLinksCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLinksCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLinksCreateResponse' from JSON`,
  );
}
