/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * JSON request body to trigger a priced challenge
 */
export type Body = {};

/**
 * Optional headers for the probe request
 */
export type Headers = {};

export type PaymentsExecuteRequest = {
  /**
   * Card identifier (sx_...)
   */
  cardId: string;
  /**
   * Card secret token (tok_...)
   */
  cardToken: string;
  /**
   * The external payment-protected URL to pay
   */
  url: string;
  /**
   * HTTP method to use when probing the URL
   */
  method?: string | undefined;
  /**
   * JSON request body to trigger a priced challenge
   */
  body?: Body | undefined;
  /**
   * Optional headers for the probe request
   */
  headers?: Headers | undefined;
};

export type PaymentsExecuteSettlement = {
  status?: string | undefined;
  txHash?: string | undefined;
};

/**
 * Payment successful
 */
export type PaymentsExecuteResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
  amountDebited?: number | undefined;
  merchantAmount?: number | undefined;
  platformFee?: number | undefined;
  token?: string | undefined;
  network?: string | undefined;
  protocol?: string | undefined;
  settlement?: PaymentsExecuteSettlement | undefined;
};

/** @internal */
export type Body$Outbound = {};

/** @internal */
export const Body$outboundSchema: z.ZodMiniType<Body$Outbound, Body> = z.object(
  {},
);

export function bodyToJSON(body: Body): string {
  return JSON.stringify(Body$outboundSchema.parse(body));
}

/** @internal */
export type Headers$Outbound = {};

/** @internal */
export const Headers$outboundSchema: z.ZodMiniType<Headers$Outbound, Headers> =
  z.object({});

export function headersToJSON(headers: Headers): string {
  return JSON.stringify(Headers$outboundSchema.parse(headers));
}

/** @internal */
export type PaymentsExecuteRequest$Outbound = {
  card_id: string;
  card_token: string;
  url: string;
  method: string;
  body?: Body$Outbound | undefined;
  headers?: Headers$Outbound | undefined;
};

/** @internal */
export const PaymentsExecuteRequest$outboundSchema: z.ZodMiniType<
  PaymentsExecuteRequest$Outbound,
  PaymentsExecuteRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    url: z.string(),
    method: z._default(z.string(), "POST"),
    body: z.optional(z.lazy(() => Body$outboundSchema)),
    headers: z.optional(z.lazy(() => Headers$outboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
    });
  }),
);

export function paymentsExecuteRequestToJSON(
  paymentsExecuteRequest: PaymentsExecuteRequest,
): string {
  return JSON.stringify(
    PaymentsExecuteRequest$outboundSchema.parse(paymentsExecuteRequest),
  );
}

/** @internal */
export const PaymentsExecuteSettlement$inboundSchema: z.ZodMiniType<
  PaymentsExecuteSettlement,
  unknown
> = z.pipe(
  z.object({
    status: types.optional(types.string()),
    tx_hash: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "tx_hash": "txHash",
    });
  }),
);

export function paymentsExecuteSettlementFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsExecuteSettlement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsExecuteSettlement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsExecuteSettlement' from JSON`,
  );
}

/** @internal */
export const PaymentsExecuteResponse$inboundSchema: z.ZodMiniType<
  PaymentsExecuteResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
    amount_debited: types.optional(types.number()),
    merchant_amount: types.optional(types.number()),
    platform_fee: types.optional(types.number()),
    token: types.optional(types.string()),
    network: types.optional(types.string()),
    protocol: types.optional(types.string()),
    settlement: types.optional(
      z.lazy(() => PaymentsExecuteSettlement$inboundSchema),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
      "amount_debited": "amountDebited",
      "merchant_amount": "merchantAmount",
      "platform_fee": "platformFee",
    });
  }),
);

export function paymentsExecuteResponseFromJSON(
  jsonString: string,
): SafeParseResult<PaymentsExecuteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentsExecuteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentsExecuteResponse' from JSON`,
  );
}
