/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type SettlementGetStatusRequest = {
  txnId: string;
};

/**
 * Settlement status
 */
export type SettlementGetStatusResponse = {
  transactionId?: string | undefined;
  status?: string | undefined;
  txHash?: string | null | undefined;
  settledAt?: Date | null | undefined;
};

/** @internal */
export type SettlementGetStatusRequest$Outbound = {
  txn_id: string;
};

/** @internal */
export const SettlementGetStatusRequest$outboundSchema: z.ZodMiniType<
  SettlementGetStatusRequest$Outbound,
  SettlementGetStatusRequest
> = z.pipe(
  z.object({
    txnId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      txnId: "txn_id",
    });
  }),
);

export function settlementGetStatusRequestToJSON(
  settlementGetStatusRequest: SettlementGetStatusRequest,
): string {
  return JSON.stringify(
    SettlementGetStatusRequest$outboundSchema.parse(settlementGetStatusRequest),
  );
}

/** @internal */
export const SettlementGetStatusResponse$inboundSchema: z.ZodMiniType<
  SettlementGetStatusResponse,
  unknown
> = z.pipe(
  z.object({
    transaction_id: types.optional(types.string()),
    status: types.optional(types.string()),
    tx_hash: z.optional(z.nullable(types.string())),
    settled_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
      "tx_hash": "txHash",
      "settled_at": "settledAt",
    });
  }),
);

export function settlementGetStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<SettlementGetStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SettlementGetStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SettlementGetStatusResponse' from JSON`,
  );
}
