/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type X402 = {
  status?: string | undefined;
  direction?: string | undefined;
  spend?: string | undefined;
  receive?: string | undefined;
  discovery?: string | undefined;
  networks?: Array<string> | undefined;
  schemes?: Array<string> | undefined;
};

export type Ap2 = {
  status?: string | undefined;
  direction?: string | undefined;
  spend?: string | undefined;
  receive?: string | undefined;
};

export type Mpp = {
  status?: string | undefined;
  direction?: string | undefined;
  spend?: string | undefined;
  receive?: string | undefined;
  capabilities?: Array<string> | undefined;
};

export type Settlement = {
  status?: string | undefined;
  feeModel?: string | undefined;
  engine?: string | undefined;
  supportedNetworks?: Array<string> | undefined;
};

export type Protocols = {
  x402?: X402 | undefined;
  ap2?: Ap2 | undefined;
  mpp?: Mpp | undefined;
  settlement?: Settlement | undefined;
};

export type CardControls = {
  mccLocks?: boolean | undefined;
  singleUse?: boolean | undefined;
  freezeUnfreeze?: boolean | undefined;
  spendingLimits?: boolean | undefined;
};

/**
 * Platform status and protocol manifest
 */
export type StatusGetResponse = {
  platform?: string | undefined;
  version?: string | undefined;
  model?: string | undefined;
  protocols?: Protocols | undefined;
  cardControls?: CardControls | undefined;
};

/** @internal */
export const X402$inboundSchema: z.ZodMiniType<X402, unknown> = z.object({
  status: types.optional(types.string()),
  direction: types.optional(types.string()),
  spend: types.optional(types.string()),
  receive: types.optional(types.string()),
  discovery: types.optional(types.string()),
  networks: types.optional(z.array(types.string())),
  schemes: types.optional(z.array(types.string())),
});

export function x402FromJSON(
  jsonString: string,
): SafeParseResult<X402, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => X402$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'X402' from JSON`,
  );
}

/** @internal */
export const Ap2$inboundSchema: z.ZodMiniType<Ap2, unknown> = z.object({
  status: types.optional(types.string()),
  direction: types.optional(types.string()),
  spend: types.optional(types.string()),
  receive: types.optional(types.string()),
});

export function ap2FromJSON(
  jsonString: string,
): SafeParseResult<Ap2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Ap2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Ap2' from JSON`,
  );
}

/** @internal */
export const Mpp$inboundSchema: z.ZodMiniType<Mpp, unknown> = z.object({
  status: types.optional(types.string()),
  direction: types.optional(types.string()),
  spend: types.optional(types.string()),
  receive: types.optional(types.string()),
  capabilities: types.optional(z.array(types.string())),
});

export function mppFromJSON(
  jsonString: string,
): SafeParseResult<Mpp, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Mpp$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Mpp' from JSON`,
  );
}

/** @internal */
export const Settlement$inboundSchema: z.ZodMiniType<Settlement, unknown> = z
  .pipe(
    z.object({
      status: types.optional(types.string()),
      fee_model: types.optional(types.string()),
      engine: types.optional(types.string()),
      supported_networks: types.optional(z.array(types.string())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "fee_model": "feeModel",
        "supported_networks": "supportedNetworks",
      });
    }),
  );

export function settlementFromJSON(
  jsonString: string,
): SafeParseResult<Settlement, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Settlement$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Settlement' from JSON`,
  );
}

/** @internal */
export const Protocols$inboundSchema: z.ZodMiniType<Protocols, unknown> = z
  .object({
    x402: types.optional(z.lazy(() => X402$inboundSchema)),
    ap2: types.optional(z.lazy(() => Ap2$inboundSchema)),
    mpp: types.optional(z.lazy(() => Mpp$inboundSchema)),
    settlement: types.optional(z.lazy(() => Settlement$inboundSchema)),
  });

export function protocolsFromJSON(
  jsonString: string,
): SafeParseResult<Protocols, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Protocols$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Protocols' from JSON`,
  );
}

/** @internal */
export const CardControls$inboundSchema: z.ZodMiniType<CardControls, unknown> =
  z.pipe(
    z.object({
      mcc_locks: types.optional(types.boolean()),
      single_use: types.optional(types.boolean()),
      freeze_unfreeze: types.optional(types.boolean()),
      spending_limits: types.optional(types.boolean()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "mcc_locks": "mccLocks",
        "single_use": "singleUse",
        "freeze_unfreeze": "freezeUnfreeze",
        "spending_limits": "spendingLimits",
      });
    }),
  );

export function cardControlsFromJSON(
  jsonString: string,
): SafeParseResult<CardControls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CardControls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CardControls' from JSON`,
  );
}

/** @internal */
export const StatusGetResponse$inboundSchema: z.ZodMiniType<
  StatusGetResponse,
  unknown
> = z.pipe(
  z.object({
    platform: types.optional(types.string()),
    version: types.optional(types.string()),
    model: types.optional(types.string()),
    protocols: types.optional(z.lazy(() => Protocols$inboundSchema)),
    card_controls: types.optional(z.lazy(() => CardControls$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "card_controls": "cardControls",
    });
  }),
);

export function statusGetResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatusGetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusGetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusGetResponse' from JSON`,
  );
}
