/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Treasury = {
  evm?: string | undefined;
  solana?: string | undefined;
};

export type Tokens = {};

/**
 * Configuration
 */
export type StatusGetConfigResponse = {
  treasury?: Treasury | undefined;
  tokens?: Tokens | undefined;
};

/** @internal */
export const Treasury$inboundSchema: z.ZodMiniType<Treasury, unknown> = z
  .object({
    evm: types.optional(types.string()),
    solana: types.optional(types.string()),
  });

export function treasuryFromJSON(
  jsonString: string,
): SafeParseResult<Treasury, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Treasury$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Treasury' from JSON`,
  );
}

/** @internal */
export const Tokens$inboundSchema: z.ZodMiniType<Tokens, unknown> = z.object(
  {},
);

export function tokensFromJSON(
  jsonString: string,
): SafeParseResult<Tokens, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Tokens$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Tokens' from JSON`,
  );
}

/** @internal */
export const StatusGetConfigResponse$inboundSchema: z.ZodMiniType<
  StatusGetConfigResponse,
  unknown
> = z.object({
  treasury: types.optional(z.lazy(() => Treasury$inboundSchema)),
  tokens: types.optional(z.lazy(() => Tokens$inboundSchema)),
});

export function statusGetConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<StatusGetConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusGetConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusGetConfigResponse' from JSON`,
  );
}
