/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Webhooks list
 */
export type WebhooksListResponse = {
  webhooks?: Array<components.Webhook> | undefined;
};

/** @internal */
export const WebhooksListResponse$inboundSchema: z.ZodMiniType<
  WebhooksListResponse,
  unknown
> = z.object({
  webhooks: types.optional(z.array(components.Webhook$inboundSchema)),
});

export function webhooksListResponseFromJSON(
  jsonString: string,
): SafeParseResult<WebhooksListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhooksListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhooksListResponse' from JSON`,
  );
}
