/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type WebhooksDeleteRequest = {
  id: string;
};

/**
 * Deleted
 */
export type WebhooksDeleteResponse = {
  success?: boolean | undefined;
};

/** @internal */
export type WebhooksDeleteRequest$Outbound = {
  id: string;
};

/** @internal */
export const WebhooksDeleteRequest$outboundSchema: z.ZodMiniType<
  WebhooksDeleteRequest$Outbound,
  WebhooksDeleteRequest
> = z.object({
  id: z.string(),
});

export function webhooksDeleteRequestToJSON(
  webhooksDeleteRequest: WebhooksDeleteRequest,
): string {
  return JSON.stringify(
    WebhooksDeleteRequest$outboundSchema.parse(webhooksDeleteRequest),
  );
}

/** @internal */
export const WebhooksDeleteResponse$inboundSchema: z.ZodMiniType<
  WebhooksDeleteResponse,
  unknown
> = z.object({
  success: types.optional(types.boolean()),
});

export function webhooksDeleteResponseFromJSON(
  jsonString: string,
): SafeParseResult<WebhooksDeleteResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhooksDeleteResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhooksDeleteResponse' from JSON`,
  );
}
