/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type WebhooksCreateRequest = {
  /**
   * HTTPS endpoint that will receive events
   */
  url: string;
  /**
   * Optional label for this webhook
   */
  description?: string | undefined;
};

/** @internal */
export type WebhooksCreateRequest$Outbound = {
  url: string;
  description?: string | undefined;
};

/** @internal */
export const WebhooksCreateRequest$outboundSchema: z.ZodMiniType<
  WebhooksCreateRequest$Outbound,
  WebhooksCreateRequest
> = z.object({
  url: z.string(),
  description: z.optional(z.string()),
});

export function webhooksCreateRequestToJSON(
  webhooksCreateRequest: WebhooksCreateRequest,
): string {
  return JSON.stringify(
    WebhooksCreateRequest$outboundSchema.parse(webhooksCreateRequest),
  );
}
