/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Gross amount to withdraw (fee is deducted from this)
 */
export type WithdrawalsCreateAmountRequest = number | string;

export type WithdrawalsCreateRequest = {
  /**
   * Gross amount to withdraw (fee is deducted from this)
   */
  amount: number | string;
  /**
   * CAIP-2 network to withdraw on
   */
  network: string;
  asset: string;
  /**
   * Destination wallet address (defaults to authenticated wallet)
   */
  toAddress?: string | undefined;
};

export type WithdrawalsCreateAvailable = number | string;

export type Requested = number | string;

export type ForbiddenWithdrawalFee = number | string;

export type BadRequestWithdrawalFee = number | string;

export type MinimumWithdrawal = number | string;

/**
 * Gross amount deducted from balance
 */
export type WithdrawalsCreateAmountResponse = number | string;

/**
 * Flat network fee retained by platform
 */
export type WithdrawalFee = number | string;

/**
 * Amount sent on-chain (amount - fee)
 */
export type NetAmount = number | string;

/**
 * Withdrawal initiated
 */
export type WithdrawalsCreateResponse = {
  success?: boolean | undefined;
  withdrawalId?: string | undefined;
  /**
   * Gross amount deducted from balance
   */
  amount?: number | string | undefined;
  /**
   * Flat network fee retained by platform
   */
  withdrawalFee?: number | string | undefined;
  /**
   * Amount sent on-chain (amount - fee)
   */
  netAmount?: number | string | undefined;
  status?: string | undefined;
  balance?: components.Balance | undefined;
};

/** @internal */
export type WithdrawalsCreateAmountRequest$Outbound = number | string;

/** @internal */
export const WithdrawalsCreateAmountRequest$outboundSchema: z.ZodMiniType<
  WithdrawalsCreateAmountRequest$Outbound,
  WithdrawalsCreateAmountRequest
> = smartUnion([z.number(), z.string()]);

export function withdrawalsCreateAmountRequestToJSON(
  withdrawalsCreateAmountRequest: WithdrawalsCreateAmountRequest,
): string {
  return JSON.stringify(
    WithdrawalsCreateAmountRequest$outboundSchema.parse(
      withdrawalsCreateAmountRequest,
    ),
  );
}

/** @internal */
export type WithdrawalsCreateRequest$Outbound = {
  amount: number | string;
  network: string;
  asset: string;
  to_address?: string | undefined;
};

/** @internal */
export const WithdrawalsCreateRequest$outboundSchema: z.ZodMiniType<
  WithdrawalsCreateRequest$Outbound,
  WithdrawalsCreateRequest
> = z.pipe(
  z.object({
    amount: smartUnion([z.number(), z.string()]),
    network: z.string(),
    asset: z.string(),
    toAddress: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      toAddress: "to_address",
    });
  }),
);

export function withdrawalsCreateRequestToJSON(
  withdrawalsCreateRequest: WithdrawalsCreateRequest,
): string {
  return JSON.stringify(
    WithdrawalsCreateRequest$outboundSchema.parse(withdrawalsCreateRequest),
  );
}

/** @internal */
export const WithdrawalsCreateAvailable$inboundSchema: z.ZodMiniType<
  WithdrawalsCreateAvailable,
  unknown
> = smartUnion([types.number(), types.string()]);

export function withdrawalsCreateAvailableFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalsCreateAvailable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalsCreateAvailable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalsCreateAvailable' from JSON`,
  );
}

/** @internal */
export const Requested$inboundSchema: z.ZodMiniType<Requested, unknown> =
  smartUnion([types.number(), types.string()]);

export function requestedFromJSON(
  jsonString: string,
): SafeParseResult<Requested, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Requested$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Requested' from JSON`,
  );
}

/** @internal */
export const ForbiddenWithdrawalFee$inboundSchema: z.ZodMiniType<
  ForbiddenWithdrawalFee,
  unknown
> = smartUnion([types.number(), types.string()]);

export function forbiddenWithdrawalFeeFromJSON(
  jsonString: string,
): SafeParseResult<ForbiddenWithdrawalFee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ForbiddenWithdrawalFee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ForbiddenWithdrawalFee' from JSON`,
  );
}

/** @internal */
export const BadRequestWithdrawalFee$inboundSchema: z.ZodMiniType<
  BadRequestWithdrawalFee,
  unknown
> = smartUnion([types.number(), types.string()]);

export function badRequestWithdrawalFeeFromJSON(
  jsonString: string,
): SafeParseResult<BadRequestWithdrawalFee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BadRequestWithdrawalFee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BadRequestWithdrawalFee' from JSON`,
  );
}

/** @internal */
export const MinimumWithdrawal$inboundSchema: z.ZodMiniType<
  MinimumWithdrawal,
  unknown
> = smartUnion([types.number(), types.string()]);

export function minimumWithdrawalFromJSON(
  jsonString: string,
): SafeParseResult<MinimumWithdrawal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MinimumWithdrawal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MinimumWithdrawal' from JSON`,
  );
}

/** @internal */
export const WithdrawalsCreateAmountResponse$inboundSchema: z.ZodMiniType<
  WithdrawalsCreateAmountResponse,
  unknown
> = smartUnion([types.number(), types.string()]);

export function withdrawalsCreateAmountResponseFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalsCreateAmountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalsCreateAmountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalsCreateAmountResponse' from JSON`,
  );
}

/** @internal */
export const WithdrawalFee$inboundSchema: z.ZodMiniType<
  WithdrawalFee,
  unknown
> = smartUnion([types.number(), types.string()]);

export function withdrawalFeeFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalFee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalFee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalFee' from JSON`,
  );
}

/** @internal */
export const NetAmount$inboundSchema: z.ZodMiniType<NetAmount, unknown> =
  smartUnion([types.number(), types.string()]);

export function netAmountFromJSON(
  jsonString: string,
): SafeParseResult<NetAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetAmount' from JSON`,
  );
}

/** @internal */
export const WithdrawalsCreateResponse$inboundSchema: z.ZodMiniType<
  WithdrawalsCreateResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    withdrawal_id: types.optional(types.string()),
    amount: types.optional(smartUnion([types.number(), types.string()])),
    withdrawal_fee: types.optional(
      smartUnion([types.number(), types.string()]),
    ),
    net_amount: types.optional(smartUnion([types.number(), types.string()])),
    status: types.optional(types.string()),
    balance: types.optional(components.Balance$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "withdrawal_id": "withdrawalId",
      "withdrawal_fee": "withdrawalFee",
      "net_amount": "netAmount",
    });
  }),
);

export function withdrawalsCreateResponseFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalsCreateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalsCreateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalsCreateResponse' from JSON`,
  );
}
