/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Filter by status
 */
export const WithdrawalsListStatus = {
  Processing: "PROCESSING",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
/**
 * Filter by status
 */
export type WithdrawalsListStatus = ClosedEnum<typeof WithdrawalsListStatus>;

export type WithdrawalsListRequest = {
  /**
   * Look up a single withdrawal by ID
   */
  id?: string | undefined;
  /**
   * Filter by status
   */
  status?: WithdrawalsListStatus | undefined;
};

/**
 * Withdrawals list
 */
export type WithdrawalsListResponse = {
  withdrawals?: Array<components.Withdrawal> | undefined;
};

/** @internal */
export const WithdrawalsListStatus$outboundSchema: z.ZodMiniEnum<
  typeof WithdrawalsListStatus
> = z.enum(WithdrawalsListStatus);

/** @internal */
export type WithdrawalsListRequest$Outbound = {
  id?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const WithdrawalsListRequest$outboundSchema: z.ZodMiniType<
  WithdrawalsListRequest$Outbound,
  WithdrawalsListRequest
> = z.object({
  id: z.optional(z.string()),
  status: z.optional(WithdrawalsListStatus$outboundSchema),
});

export function withdrawalsListRequestToJSON(
  withdrawalsListRequest: WithdrawalsListRequest,
): string {
  return JSON.stringify(
    WithdrawalsListRequest$outboundSchema.parse(withdrawalsListRequest),
  );
}

/** @internal */
export const WithdrawalsListResponse$inboundSchema: z.ZodMiniType<
  WithdrawalsListResponse,
  unknown
> = z.object({
  withdrawals: types.optional(z.array(components.Withdrawal$inboundSchema)),
});

export function withdrawalsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalsListResponse' from JSON`,
  );
}
