/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type X402DiscoverRequest = {
  url: string;
};

export type X402DiscoverAmount = number | string;

/**
 * Discovery result
 */
export type X402DiscoverResponse = {
  supportsX402?: boolean | undefined;
  paymentAddress?: string | undefined;
  amount?: number | string | undefined;
  asset?: string | undefined;
};

/** @internal */
export type X402DiscoverRequest$Outbound = {
  url: string;
};

/** @internal */
export const X402DiscoverRequest$outboundSchema: z.ZodMiniType<
  X402DiscoverRequest$Outbound,
  X402DiscoverRequest
> = z.object({
  url: z.string(),
});

export function x402DiscoverRequestToJSON(
  x402DiscoverRequest: X402DiscoverRequest,
): string {
  return JSON.stringify(
    X402DiscoverRequest$outboundSchema.parse(x402DiscoverRequest),
  );
}

/** @internal */
export const X402DiscoverAmount$inboundSchema: z.ZodMiniType<
  X402DiscoverAmount,
  unknown
> = smartUnion([types.number(), types.string()]);

export function x402DiscoverAmountFromJSON(
  jsonString: string,
): SafeParseResult<X402DiscoverAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => X402DiscoverAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'X402DiscoverAmount' from JSON`,
  );
}

/** @internal */
export const X402DiscoverResponse$inboundSchema: z.ZodMiniType<
  X402DiscoverResponse,
  unknown
> = z.pipe(
  z.object({
    supports_x402: types.optional(types.boolean()),
    payment_address: types.optional(types.string()),
    amount: types.optional(smartUnion([types.number(), types.string()])),
    asset: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "supports_x402": "supportsX402",
      "payment_address": "paymentAddress",
    });
  }),
);

export function x402DiscoverResponseFromJSON(
  jsonString: string,
): SafeParseResult<X402DiscoverResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => X402DiscoverResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'X402DiscoverResponse' from JSON`,
  );
}
