/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type X402PayRequest = {
  /**
   * Card identifier (sx_...)
   */
  cardId: string;
  /**
   * Card secret token (tok_...)
   */
  cardToken: string;
  /**
   * Payment amount in USDC
   */
  amount: number;
  /**
   * Merchant identifier
   */
  merchant?: string | undefined;
  /**
   * Merchant wallet for settlement
   */
  merchantAddress?: string | undefined;
  /**
   * Merchant category code
   */
  mcc?: string | undefined;
  /**
   * URL being paid for
   */
  resourceUrl?: string | undefined;
  network?: string | undefined;
};

/**
 * 'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain.
 */
export const Environment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
/**
 * 'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain.
 */
export type Environment = OpenEnum<typeof Environment>;

/**
 * Payment authorized
 */
export type X402PayResponse = {
  success?: boolean | undefined;
  transactionId?: string | undefined;
  cardId?: string | undefined;
  amount?: number | undefined;
  network?: string | undefined;
  /**
   * 'sandbox' for testnet networks (e.g. eip155:84532), 'production' for mainnet. Sandbox transactions deduct balance but are never settled on-chain.
   */
  environment?: Environment | undefined;
  resourceUrl?: string | null | undefined;
  protocol?: string | undefined;
  timestamp?: Date | undefined;
  paymentHeader?: components.PaymentHeader | undefined;
};

/** @internal */
export type X402PayRequest$Outbound = {
  card_id: string;
  card_token: string;
  amount: number;
  merchant?: string | undefined;
  merchant_address?: string | undefined;
  mcc?: string | undefined;
  resource_url?: string | undefined;
  network: string;
};

/** @internal */
export const X402PayRequest$outboundSchema: z.ZodMiniType<
  X402PayRequest$Outbound,
  X402PayRequest
> = z.pipe(
  z.object({
    cardId: z.string(),
    cardToken: z.string(),
    amount: z.number(),
    merchant: z.optional(z.string()),
    merchantAddress: z.optional(z.string()),
    mcc: z.optional(z.string()),
    resourceUrl: z.optional(z.string()),
    network: z._default(z.string(), "eip155:8453"),
  }),
  z.transform((v) => {
    return remap$(v, {
      cardId: "card_id",
      cardToken: "card_token",
      merchantAddress: "merchant_address",
      resourceUrl: "resource_url",
    });
  }),
);

export function x402PayRequestToJSON(x402PayRequest: X402PayRequest): string {
  return JSON.stringify(X402PayRequest$outboundSchema.parse(x402PayRequest));
}

/** @internal */
export const Environment$inboundSchema: z.ZodMiniType<Environment, unknown> =
  openEnums.inboundSchema(Environment);

/** @internal */
export const X402PayResponse$inboundSchema: z.ZodMiniType<
  X402PayResponse,
  unknown
> = z.pipe(
  z.object({
    success: types.optional(types.boolean()),
    transaction_id: types.optional(types.string()),
    card_id: types.optional(types.string()),
    amount: types.optional(types.number()),
    network: types.optional(types.string()),
    environment: types.optional(Environment$inboundSchema),
    resource_url: z.optional(z.nullable(types.string())),
    protocol: types.optional(types.string()),
    timestamp: types.optional(types.date()),
    payment_header: types.optional(components.PaymentHeader$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "transaction_id": "transactionId",
      "card_id": "cardId",
      "resource_url": "resourceUrl",
      "payment_header": "paymentHeader",
    });
  }),
);

export function x402PayResponseFromJSON(
  jsonString: string,
): SafeParseResult<X402PayResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => X402PayResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'X402PayResponse' from JSON`,
  );
}
