/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PaymentHeader = {};

export type X402ReceiveRequest = {
  paymentHeader?: PaymentHeader | undefined;
  resourceUrl?: string | undefined;
};

/**
 * Payment verified
 */
export type X402ReceiveResponse = {
  verified?: boolean | undefined;
  resource?: string | undefined;
};

/** @internal */
export type PaymentHeader$Outbound = {};

/** @internal */
export const PaymentHeader$outboundSchema: z.ZodMiniType<
  PaymentHeader$Outbound,
  PaymentHeader
> = z.object({});

export function paymentHeaderToJSON(paymentHeader: PaymentHeader): string {
  return JSON.stringify(PaymentHeader$outboundSchema.parse(paymentHeader));
}

/** @internal */
export type X402ReceiveRequest$Outbound = {
  payment_header?: PaymentHeader$Outbound | undefined;
  resource_url?: string | undefined;
};

/** @internal */
export const X402ReceiveRequest$outboundSchema: z.ZodMiniType<
  X402ReceiveRequest$Outbound,
  X402ReceiveRequest
> = z.pipe(
  z.object({
    paymentHeader: z.optional(z.lazy(() => PaymentHeader$outboundSchema)),
    resourceUrl: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      paymentHeader: "payment_header",
      resourceUrl: "resource_url",
    });
  }),
);

export function x402ReceiveRequestToJSON(
  x402ReceiveRequest: X402ReceiveRequest,
): string {
  return JSON.stringify(
    X402ReceiveRequest$outboundSchema.parse(x402ReceiveRequest),
  );
}

/** @internal */
export const X402ReceiveResponse$inboundSchema: z.ZodMiniType<
  X402ReceiveResponse,
  unknown
> = z.object({
  verified: types.optional(types.boolean()),
  resource: types.optional(types.string()),
});

export function x402ReceiveResponseFromJSON(
  jsonString: string,
): SafeParseResult<X402ReceiveResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => X402ReceiveResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'X402ReceiveResponse' from JSON`,
  );
}
