/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const ApiKeyStatus = {
  Active: "active",
  Revoked: "revoked",
} as const;
export type ApiKeyStatus = OpenEnum<typeof ApiKeyStatus>;

export type ApiKey = {
  keyHash?: string | undefined;
  keyHint?: string | undefined;
  status?: ApiKeyStatus | undefined;
  createdAt?: Date | undefined;
  revokedAt?: Date | null | undefined;
};

/** @internal */
export const ApiKeyStatus$inboundSchema: z.ZodMiniType<ApiKeyStatus, unknown> =
  openEnums.inboundSchema(ApiKeyStatus);

/** @internal */
export const ApiKey$inboundSchema: z.ZodMiniType<ApiKey, unknown> = z.pipe(
  z.object({
    key_hash: types.optional(types.string()),
    key_hint: types.optional(types.string()),
    status: types.optional(ApiKeyStatus$inboundSchema),
    created_at: types.optional(types.date()),
    revoked_at: z.optional(z.nullable(types.date())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "key_hash": "keyHash",
      "key_hint": "keyHint",
      "created_at": "createdAt",
      "revoked_at": "revokedAt",
    });
  }),
);

export function apiKeyFromJSON(
  jsonString: string,
): SafeParseResult<ApiKey, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ApiKey$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ApiKey' from JSON`,
  );
}
