/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type Balance = {
  totalFunded?: number | undefined;
  totalAllocated?: number | undefined;
  totalSpent?: number | undefined;
  totalWithdrawn?: number | undefined;
  available?: number | undefined;
  network?: string | undefined;
  asset?: string | undefined;
};

/** @internal */
export const Balance$inboundSchema: z.ZodMiniType<Balance, unknown> = z.pipe(
  z.object({
    total_funded: types.optional(types.number()),
    total_allocated: types.optional(types.number()),
    total_spent: types.optional(types.number()),
    total_withdrawn: types.optional(types.number()),
    available: types.optional(types.number()),
    network: types.optional(types.string()),
    asset: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "total_funded": "totalFunded",
      "total_allocated": "totalAllocated",
      "total_spent": "totalSpent",
      "total_withdrawn": "totalWithdrawn",
    });
  }),
);

export function balanceFromJSON(
  jsonString: string,
): SafeParseResult<Balance, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Balance$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Balance' from JSON`,
  );
}
