/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type BalanceErrorAvailable = number | string;

export type Requested = number | string;

/** @internal */
export const BalanceErrorAvailable$inboundSchema: z.ZodMiniType<
  BalanceErrorAvailable,
  unknown
> = smartUnion([types.number(), types.string()]);

export function balanceErrorAvailableFromJSON(
  jsonString: string,
): SafeParseResult<BalanceErrorAvailable, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BalanceErrorAvailable$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BalanceErrorAvailable' from JSON`,
  );
}

/** @internal */
export const Requested$inboundSchema: z.ZodMiniType<Requested, unknown> =
  smartUnion([types.number(), types.string()]);

export function requestedFromJSON(
  jsonString: string,
): SafeParseResult<Requested, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Requested$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Requested' from JSON`,
  );
}
