/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const CardStatus = {
  Active: "ACTIVE",
  Frozen: "FROZEN",
  Expired: "EXPIRED",
  Used: "USED",
  PendingFunding: "PENDING_FUNDING",
  FundingFailed: "FUNDING_FAILED",
} as const;
export type CardStatus = OpenEnum<typeof CardStatus>;

export const SingleUse = {
  Zero: 0,
  One: 1,
} as const;
export type SingleUse = OpenEnum<typeof SingleUse>;

export type Card = {
  id?: string | undefined;
  token?: string | undefined;
  purpose?: string | undefined;
  limitAmount?: number | undefined;
  status?: CardStatus | undefined;
  mccLocks?: string | undefined;
  singleUse?: SingleUse | undefined;
  expiresAt?: Date | null | undefined;
  fundingNetwork?: string | undefined;
  fundingAsset?: string | undefined;
  walletAddress?: string | undefined;
  balance?: number | undefined;
  remaining?: number | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const CardStatus$inboundSchema: z.ZodMiniType<CardStatus, unknown> =
  openEnums.inboundSchema(CardStatus);

/** @internal */
export const SingleUse$inboundSchema: z.ZodMiniType<SingleUse, unknown> =
  openEnums.inboundSchemaInt(SingleUse);

/** @internal */
export const Card$inboundSchema: z.ZodMiniType<Card, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    token: types.optional(types.string()),
    purpose: types.optional(types.string()),
    limit_amount: types.optional(types.number()),
    status: types.optional(CardStatus$inboundSchema),
    mcc_locks: types.optional(types.string()),
    single_use: types.optional(SingleUse$inboundSchema),
    expires_at: z.optional(z.nullable(types.date())),
    funding_network: types.optional(types.string()),
    funding_asset: types.optional(types.string()),
    wallet_address: types.optional(types.string()),
    balance: types.optional(types.number()),
    remaining: types.optional(types.number()),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "limit_amount": "limitAmount",
      "mcc_locks": "mccLocks",
      "single_use": "singleUse",
      "expires_at": "expiresAt",
      "funding_network": "fundingNetwork",
      "funding_asset": "fundingAsset",
      "wallet_address": "walletAddress",
      "created_at": "createdAt",
    });
  }),
);

export function cardFromJSON(
  jsonString: string,
): SafeParseResult<Card, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Card$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Card' from JSON`,
  );
}
