/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const PayLinkStatus = {
  Active: "ACTIVE",
  Expired: "EXPIRED",
  Cancelled: "CANCELLED",
} as const;
export type PayLinkStatus = OpenEnum<typeof PayLinkStatus>;

export type PayLink = {
  id?: string | undefined;
  code?: string | undefined;
  url?: string | undefined;
  amount?: number | null | undefined;
  asset?: string | undefined;
  network?: string | undefined;
  memo?: string | undefined;
  status?: PayLinkStatus | undefined;
  uses?: number | undefined;
  maxUses?: number | undefined;
  expiresAt?: Date | null | undefined;
  qrSvg?: string | undefined;
};

/** @internal */
export const PayLinkStatus$inboundSchema: z.ZodMiniType<
  PayLinkStatus,
  unknown
> = openEnums.inboundSchema(PayLinkStatus);

/** @internal */
export const PayLink$inboundSchema: z.ZodMiniType<PayLink, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    code: types.optional(types.string()),
    url: types.optional(types.string()),
    amount: z.optional(z.nullable(types.number())),
    asset: types.optional(types.string()),
    network: types.optional(types.string()),
    memo: types.optional(types.string()),
    status: types.optional(PayLinkStatus$inboundSchema),
    uses: types.optional(types.number()),
    max_uses: types.optional(types.number()),
    expires_at: z.optional(z.nullable(types.date())),
    qr_svg: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "max_uses": "maxUses",
      "expires_at": "expiresAt",
      "qr_svg": "qrSvg",
    });
  }),
);

export function payLinkFromJSON(
  jsonString: string,
): SafeParseResult<PayLink, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayLink$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayLink' from JSON`,
  );
}
