/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const Type = {
  PaymentSettled: "payment.settled",
} as const;
export type Type = ClosedEnum<typeof Type>;

export const PaymentSettledEventProtocol = {
  X402: "x402",
  Ap2: "ap2",
  Mpp: "mpp",
} as const;
export type PaymentSettledEventProtocol = ClosedEnum<
  typeof PaymentSettledEventProtocol
>;

export const Mode = {
  ExternalProtocol: "external_protocol",
  Protocol: "protocol",
} as const;
export type Mode = ClosedEnum<typeof Mode>;

export type PaymentSettledEventAmount = number | string;

export type Fee = number | string;

export type NetAmount = number | string;

export type Data = {
  settlementId?: string | undefined;
  payLinkCode?: string | undefined;
  protocol?: PaymentSettledEventProtocol | undefined;
  mode?: Mode | undefined;
  amount?: number | string | undefined;
  fee?: number | string | undefined;
  netAmount?: number | string | undefined;
  asset?: string | undefined;
  network?: string | undefined;
  txHash?: string | null | undefined;
  receiptId?: string | null | undefined;
  receiverCardId?: string | undefined;
  memo?: string | null | undefined;
};

/**
 * Body POSTed to a registered webhook when a pay link settles. Signed via the X-mag3nt-Signature header (t=<unix>,v1=<hex hmac-sha256 of `${t}.${rawBody}`>). Verify with your webhook secret before acting.
 *
 * @remarks
 */
export type PaymentSettledEvent = {
  id?: string | undefined;
  type?: Type | undefined;
  /**
   * Unix timestamp (seconds)
   */
  created?: number | undefined;
  data?: Data | undefined;
};

/** @internal */
export const Type$inboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);
/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> =
  Type$inboundSchema;

/** @internal */
export const PaymentSettledEventProtocol$inboundSchema: z.ZodMiniEnum<
  typeof PaymentSettledEventProtocol
> = z.enum(PaymentSettledEventProtocol);
/** @internal */
export const PaymentSettledEventProtocol$outboundSchema: z.ZodMiniEnum<
  typeof PaymentSettledEventProtocol
> = PaymentSettledEventProtocol$inboundSchema;

/** @internal */
export const Mode$inboundSchema: z.ZodMiniEnum<typeof Mode> = z.enum(Mode);
/** @internal */
export const Mode$outboundSchema: z.ZodMiniEnum<typeof Mode> =
  Mode$inboundSchema;

/** @internal */
export const PaymentSettledEventAmount$inboundSchema: z.ZodMiniType<
  PaymentSettledEventAmount,
  unknown
> = smartUnion([types.number(), types.string()]);
/** @internal */
export type PaymentSettledEventAmount$Outbound = number | string;

/** @internal */
export const PaymentSettledEventAmount$outboundSchema: z.ZodMiniType<
  PaymentSettledEventAmount$Outbound,
  PaymentSettledEventAmount
> = smartUnion([z.number(), z.string()]);

export function paymentSettledEventAmountToJSON(
  paymentSettledEventAmount: PaymentSettledEventAmount,
): string {
  return JSON.stringify(
    PaymentSettledEventAmount$outboundSchema.parse(paymentSettledEventAmount),
  );
}
export function paymentSettledEventAmountFromJSON(
  jsonString: string,
): SafeParseResult<PaymentSettledEventAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentSettledEventAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentSettledEventAmount' from JSON`,
  );
}

/** @internal */
export const Fee$inboundSchema: z.ZodMiniType<Fee, unknown> = smartUnion([
  types.number(),
  types.string(),
]);
/** @internal */
export type Fee$Outbound = number | string;

/** @internal */
export const Fee$outboundSchema: z.ZodMiniType<Fee$Outbound, Fee> = smartUnion([
  z.number(),
  z.string(),
]);

export function feeToJSON(fee: Fee): string {
  return JSON.stringify(Fee$outboundSchema.parse(fee));
}
export function feeFromJSON(
  jsonString: string,
): SafeParseResult<Fee, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Fee$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Fee' from JSON`,
  );
}

/** @internal */
export const NetAmount$inboundSchema: z.ZodMiniType<NetAmount, unknown> =
  smartUnion([types.number(), types.string()]);
/** @internal */
export type NetAmount$Outbound = number | string;

/** @internal */
export const NetAmount$outboundSchema: z.ZodMiniType<
  NetAmount$Outbound,
  NetAmount
> = smartUnion([z.number(), z.string()]);

export function netAmountToJSON(netAmount: NetAmount): string {
  return JSON.stringify(NetAmount$outboundSchema.parse(netAmount));
}
export function netAmountFromJSON(
  jsonString: string,
): SafeParseResult<NetAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetAmount' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.pipe(
  z.object({
    settlement_id: types.optional(types.string()),
    pay_link_code: types.optional(types.string()),
    protocol: types.optional(PaymentSettledEventProtocol$inboundSchema),
    mode: types.optional(Mode$inboundSchema),
    amount: types.optional(smartUnion([types.number(), types.string()])),
    fee: types.optional(smartUnion([types.number(), types.string()])),
    net_amount: types.optional(smartUnion([types.number(), types.string()])),
    asset: types.optional(types.string()),
    network: types.optional(types.string()),
    tx_hash: z.optional(z.nullable(types.string())),
    receipt_id: z.optional(z.nullable(types.string())),
    receiver_card_id: types.optional(types.string()),
    memo: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "settlement_id": "settlementId",
      "pay_link_code": "payLinkCode",
      "net_amount": "netAmount",
      "tx_hash": "txHash",
      "receipt_id": "receiptId",
      "receiver_card_id": "receiverCardId",
    });
  }),
);
/** @internal */
export type Data$Outbound = {
  settlement_id?: string | undefined;
  pay_link_code?: string | undefined;
  protocol?: string | undefined;
  mode?: string | undefined;
  amount?: number | string | undefined;
  fee?: number | string | undefined;
  net_amount?: number | string | undefined;
  asset?: string | undefined;
  network?: string | undefined;
  tx_hash?: string | null | undefined;
  receipt_id?: string | null | undefined;
  receiver_card_id?: string | undefined;
  memo?: string | null | undefined;
};

/** @internal */
export const Data$outboundSchema: z.ZodMiniType<Data$Outbound, Data> = z.pipe(
  z.object({
    settlementId: z.optional(z.string()),
    payLinkCode: z.optional(z.string()),
    protocol: z.optional(PaymentSettledEventProtocol$outboundSchema),
    mode: z.optional(Mode$outboundSchema),
    amount: z.optional(smartUnion([z.number(), z.string()])),
    fee: z.optional(smartUnion([z.number(), z.string()])),
    netAmount: z.optional(smartUnion([z.number(), z.string()])),
    asset: z.optional(z.string()),
    network: z.optional(z.string()),
    txHash: z.optional(z.nullable(z.string())),
    receiptId: z.optional(z.nullable(z.string())),
    receiverCardId: z.optional(z.string()),
    memo: z.optional(z.nullable(z.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      settlementId: "settlement_id",
      payLinkCode: "pay_link_code",
      netAmount: "net_amount",
      txHash: "tx_hash",
      receiptId: "receipt_id",
      receiverCardId: "receiver_card_id",
    });
  }),
);

export function dataToJSON(data: Data): string {
  return JSON.stringify(Data$outboundSchema.parse(data));
}
export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const PaymentSettledEvent$inboundSchema: z.ZodMiniType<
  PaymentSettledEvent,
  unknown
> = z.object({
  id: types.optional(types.string()),
  type: types.optional(Type$inboundSchema),
  created: types.optional(types.number()),
  data: types.optional(z.lazy(() => Data$inboundSchema)),
});
/** @internal */
export type PaymentSettledEvent$Outbound = {
  id?: string | undefined;
  type?: string | undefined;
  created?: number | undefined;
  data?: Data$Outbound | undefined;
};

/** @internal */
export const PaymentSettledEvent$outboundSchema: z.ZodMiniType<
  PaymentSettledEvent$Outbound,
  PaymentSettledEvent
> = z.object({
  id: z.optional(z.string()),
  type: z.optional(Type$outboundSchema),
  created: z.optional(z.int()),
  data: z.optional(z.lazy(() => Data$outboundSchema)),
});

export function paymentSettledEventToJSON(
  paymentSettledEvent: PaymentSettledEvent,
): string {
  return JSON.stringify(
    PaymentSettledEvent$outboundSchema.parse(paymentSettledEvent),
  );
}
export function paymentSettledEventFromJSON(
  jsonString: string,
): SafeParseResult<PaymentSettledEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentSettledEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentSettledEvent' from JSON`,
  );
}
