/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * 'sandbox' for testnet networks, 'production' for mainnet
 */
export const XMag3ntEnvironment = {
  Sandbox: "sandbox",
  Production: "production",
} as const;
/**
 * 'sandbox' for testnet networks, 'production' for mainnet
 */
export type XMag3ntEnvironment = OpenEnum<typeof XMag3ntEnvironment>;

export type PaymentHeader = {
  xMag3ntTransaction?: string | undefined;
  xMag3ntCard?: string | undefined;
  xMag3ntAmount?: string | undefined;
  xMag3ntProtocol?: string | undefined;
  /**
   * CAIP-2 network identifier
   */
  xMag3ntNetwork?: string | undefined;
  /**
   * 'sandbox' for testnet networks, 'production' for mainnet
   */
  xMag3ntEnvironment?: XMag3ntEnvironment | undefined;
};

/** @internal */
export const XMag3ntEnvironment$inboundSchema: z.ZodMiniType<
  XMag3ntEnvironment,
  unknown
> = openEnums.inboundSchema(XMag3ntEnvironment);

/** @internal */
export const PaymentHeader$inboundSchema: z.ZodMiniType<
  PaymentHeader,
  unknown
> = z.pipe(
  z.object({
    "X-mag3nt-Transaction": types.optional(types.string()),
    "X-mag3nt-Card": types.optional(types.string()),
    "X-mag3nt-Amount": types.optional(types.string()),
    "X-mag3nt-Protocol": types.optional(types.string()),
    "X-mag3nt-Network": types.optional(types.string()),
    "X-mag3nt-Environment": types.optional(XMag3ntEnvironment$inboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      "X-mag3nt-Transaction": "xMag3ntTransaction",
      "X-mag3nt-Card": "xMag3ntCard",
      "X-mag3nt-Amount": "xMag3ntAmount",
      "X-mag3nt-Protocol": "xMag3ntProtocol",
      "X-mag3nt-Network": "xMag3ntNetwork",
      "X-mag3nt-Environment": "xMag3ntEnvironment",
    });
  }),
);

export function paymentHeaderFromJSON(
  jsonString: string,
): SafeParseResult<PaymentHeader, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentHeader$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentHeader' from JSON`,
  );
}
