/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const Protocol = {
  X402: "x402",
  Ap2: "ap2",
  Mpp: "mpp",
} as const;
export type Protocol = OpenEnum<typeof Protocol>;

export type Transaction = {
  id?: string | undefined;
  cardId?: string | undefined;
  amount?: number | undefined;
  merchant?: string | undefined;
  protocol?: Protocol | undefined;
  status?: string | undefined;
  txHash?: string | undefined;
  network?: string | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Protocol$inboundSchema: z.ZodMiniType<Protocol, unknown> =
  openEnums.inboundSchema(Protocol);

/** @internal */
export const Transaction$inboundSchema: z.ZodMiniType<Transaction, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      card_id: types.optional(types.string()),
      amount: types.optional(types.number()),
      merchant: types.optional(types.string()),
      protocol: types.optional(Protocol$inboundSchema),
      status: types.optional(types.string()),
      tx_hash: types.optional(types.string()),
      network: types.optional(types.string()),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "card_id": "cardId",
        "tx_hash": "txHash",
        "created_at": "createdAt",
      });
    }),
  );

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}
