/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type TransactionAmount = number | string;

export const TransactionProtocol = {
  X402: "x402",
  Ap2: "ap2",
  Mpp: "mpp",
} as const;
export type TransactionProtocol = OpenEnum<typeof TransactionProtocol>;

export type Transaction = {
  id?: string | undefined;
  cardId?: string | undefined;
  amount?: number | string | undefined;
  merchant?: string | undefined;
  protocol?: TransactionProtocol | undefined;
  status?: string | undefined;
  txHash?: string | undefined;
  network?: string | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const TransactionAmount$inboundSchema: z.ZodMiniType<
  TransactionAmount,
  unknown
> = smartUnion([types.number(), types.string()]);

export function transactionAmountFromJSON(
  jsonString: string,
): SafeParseResult<TransactionAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionAmount' from JSON`,
  );
}

/** @internal */
export const TransactionProtocol$inboundSchema: z.ZodMiniType<
  TransactionProtocol,
  unknown
> = openEnums.inboundSchema(TransactionProtocol);

/** @internal */
export const Transaction$inboundSchema: z.ZodMiniType<Transaction, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      card_id: types.optional(types.string()),
      amount: types.optional(smartUnion([types.number(), types.string()])),
      merchant: types.optional(types.string()),
      protocol: types.optional(TransactionProtocol$inboundSchema),
      status: types.optional(types.string()),
      tx_hash: types.optional(types.string()),
      network: types.optional(types.string()),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "card_id": "cardId",
        "tx_hash": "txHash",
        "created_at": "createdAt",
      });
    }),
  );

export function transactionFromJSON(
  jsonString: string,
): SafeParseResult<Transaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Transaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Transaction' from JSON`,
  );
}
