/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Returned ONLY when a webhook is created. The secret is used to verify the X-mag3nt-Signature header on delivered events and cannot be retrieved again.
 *
 * @remarks
 */
export type WebhookSecret = {
  id?: string | undefined;
  url?: string | undefined;
  description?: string | undefined;
  status?: string | undefined;
  /**
   * HMAC signing secret (whsec_...). Store securely; shown once.
   */
  secret?: string | undefined;
  note?: string | undefined;
};

/** @internal */
export const WebhookSecret$inboundSchema: z.ZodMiniType<
  WebhookSecret,
  unknown
> = z.object({
  id: types.optional(types.string()),
  url: types.optional(types.string()),
  description: types.optional(types.string()),
  status: types.optional(types.string()),
  secret: types.optional(types.string()),
  note: types.optional(types.string()),
});

export function webhookSecretFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSecret, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookSecret$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSecret' from JSON`,
  );
}
