/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const WebhookStatus = {
  Active: "ACTIVE",
  Disabled: "DISABLED",
} as const;
export type WebhookStatus = OpenEnum<typeof WebhookStatus>;

export type Webhook = {
  id?: string | undefined;
  url?: string | undefined;
  description?: string | undefined;
  status?: WebhookStatus | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const WebhookStatus$inboundSchema: z.ZodMiniType<
  WebhookStatus,
  unknown
> = openEnums.inboundSchema(WebhookStatus);

/** @internal */
export const Webhook$inboundSchema: z.ZodMiniType<Webhook, unknown> = z.pipe(
  z.object({
    id: types.optional(types.string()),
    url: types.optional(types.string()),
    description: types.optional(types.string()),
    status: types.optional(WebhookStatus$inboundSchema),
    created_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  }),
);

export function webhookFromJSON(
  jsonString: string,
): SafeParseResult<Webhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Webhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Webhook' from JSON`,
  );
}
