/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smart-union.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export const Chain = {
  Eip155: "eip155",
  Solana: "solana",
} as const;
export type Chain = OpenEnum<typeof Chain>;

/**
 * Gross amount deducted from balance (includes fee)
 */
export type WithdrawalAmount = number | string;

/**
 * Platform withdrawal fee
 */
export type FeeAmount = number | string;

export const WithdrawalStatus = {
  Processing: "PROCESSING",
  Completed: "COMPLETED",
  Failed: "FAILED",
} as const;
export type WithdrawalStatus = OpenEnum<typeof WithdrawalStatus>;

export type Withdrawal = {
  id?: string | undefined;
  walletAddress?: string | undefined;
  chain?: Chain | undefined;
  asset?: string | undefined;
  network?: string | undefined;
  /**
   * Gross amount deducted from balance (includes fee)
   */
  amount?: number | string | undefined;
  /**
   * Platform withdrawal fee
   */
  feeAmount?: number | string | undefined;
  toAddress?: string | undefined;
  status?: WithdrawalStatus | undefined;
  /**
   * On-chain transaction hash (populated on completion)
   */
  txHash?: string | null | undefined;
  createdAt?: Date | undefined;
};

/** @internal */
export const Chain$inboundSchema: z.ZodMiniType<Chain, unknown> = openEnums
  .inboundSchema(Chain);

/** @internal */
export const WithdrawalAmount$inboundSchema: z.ZodMiniType<
  WithdrawalAmount,
  unknown
> = smartUnion([types.number(), types.string()]);

export function withdrawalAmountFromJSON(
  jsonString: string,
): SafeParseResult<WithdrawalAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WithdrawalAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WithdrawalAmount' from JSON`,
  );
}

/** @internal */
export const FeeAmount$inboundSchema: z.ZodMiniType<FeeAmount, unknown> =
  smartUnion([types.number(), types.string()]);

export function feeAmountFromJSON(
  jsonString: string,
): SafeParseResult<FeeAmount, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FeeAmount$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FeeAmount' from JSON`,
  );
}

/** @internal */
export const WithdrawalStatus$inboundSchema: z.ZodMiniType<
  WithdrawalStatus,
  unknown
> = openEnums.inboundSchema(WithdrawalStatus);

/** @internal */
export const Withdrawal$inboundSchema: z.ZodMiniType<Withdrawal, unknown> = z
  .pipe(
    z.object({
      id: types.optional(types.string()),
      wallet_address: types.optional(types.string()),
      chain: types.optional(Chain$inboundSchema),
      asset: types.optional(types.string()),
      network: types.optional(types.string()),
      amount: types.optional(smartUnion([types.number(), types.string()])),
      fee_amount: types.optional(smartUnion([types.number(), types.string()])),
      to_address: types.optional(types.string()),
      status: types.optional(WithdrawalStatus$inboundSchema),
      tx_hash: z.optional(z.nullable(types.string())),
      created_at: types.optional(types.date()),
    }),
    z.transform((v) => {
      return remap$(v, {
        "wallet_address": "walletAddress",
        "fee_amount": "feeAmount",
        "to_address": "toAddress",
        "tx_hash": "txHash",
        "created_at": "createdAt",
      });
    }),
  );

export function withdrawalFromJSON(
  jsonString: string,
): SafeParseResult<Withdrawal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Withdrawal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Withdrawal' from JSON`,
  );
}
